<?php

declare(strict_types=1);

return [
    // 'name' => 'Demand Generation',
    // 'slug' => 'demand-generation',

    // 'seo' => [
    //     'title' => 'Demand Generation Services | SEO, PPC & Email Marketing | Skale',
    //     'description' => 'Build a connected demand generation system using SEO, paid media, email marketing, conversion optimization, and analytics to create more qualified opportunities.',
    //     'canonical' => '/solutions/demand-generation',
    //     'robots' => 'index,follow',
    //     'ogType' => 'website',
    //     'ogImage' => null,
    // ],

    'sections' => [
        'hero' => [
            'enabled' => true,
            'id' => 'demand-generation-hero',
            'tag' => 'section',
            'class' => 'hero hero-demand-generation position-relative overflow-hidden text-white',
            'containerClass' => 'container position-relative',
            'rowClass' => 'row align-items-center g-5',
            'contentColumnClass' => 'col-lg-7',
            'formColumnClass' => 'col-lg-5',
            'contentClass' => 'hero-copy pe-lg-4',
            'eyebrow' => 'Demand Generation',
            'eyebrowClass' => 'eyebrow eyebrow-light',
            'heading' => 'Turn attention into a predictable pipeline of',
            'highlight' => 'qualified opportunities.',
            'headingTag' => 'h1',
            'headingClass' => 'display-4 fw-bold',
            'highlightClass' => 'text-highlight text-accent',
            'description' => 'Skale connects SEO, paid media, email, landing pages, conversion strategy, and reporting into one measurable system built to attract the right people and move them toward a real sales conversation.',
            'descriptionClass' => 'hero-lead lead mt-4 mb-0 text-white-75',
            'background' => [
                'class' => 'hero-demand-generation-bg',
                'overlayClass' => 'hero-demand-generation-overlay',
                'decorations' => [
                    [
                        'class' => 'hero-orb hero-orb-one',
                        'ariaHidden' => true,
                    ],
                    [
                        'class' => 'hero-orb hero-orb-two',
                        'ariaHidden' => true,
                    ],
                    [
                        'class' => 'hero-grid',
                        'ariaHidden' => true,
                    ],
                ],
            ],
            'benefits' => [
                'class' => 'hero-checks hero-checks-light',
                'ariaLabel' => 'Demand generation benefits',
                'iconClass' => 'bi bi-check-circle-fill text-accent',
                'items' => [
                    'Strategy built around revenue—not vanity metrics',
                    'Channels that reinforce one another',
                    'Clear reporting from first click to qualified lead',
                ],
            ],
            'buttons' => [
                'wrapperClass' => 'd-flex flex-column flex-sm-row gap-3',
                'items' => [
                    [
                        'label' => 'Get Your Free Demand Review',
                        'url' => '#consultation',
                        'class' => 'btn btn-primary btn-lg',
                        'target' => null,
                        'rel' => null,
                    ],
                    [
                        'label' => 'See the Growth System',
                        'url' => '#how-it-works',
                        'class' => 'btn btn-outline-dark btn-lg',
                        'target' => null,
                        'rel' => null,
                    ],
                ],
            ],
            'note' => [
                'text' => 'No channel pitch. We start by finding where your current marketing is losing attention, leads, or revenue.',
                'class' => 'hero-note hero-note-light',
                'iconClass' => 'bi bi-shield-check',
            ],
            'form' => [
                'enabled' => true,
                'anchorId' => 'consultation',
                'wrapperClass' => 'hero-form-wrap',
                'cardClass' => 'lead-form-card lead-form-card-dark-accent',
                'headerClass' => 'mb-4',
                'badge' => 'Free 30-minute demand review',
                'badgeClass' => 'badge text-bg-light border mb-3',
                'heading' => 'Find the biggest gap in your lead flow',
                'headingTag' => 'h2',
                'headingClass' => 'h3 mb-2',
                'description' => 'Tell us what you are doing today. We will help identify where your traffic, funnel, follow-up, or measurement may be breaking down.',
                'descriptionClass' => 'mb-0 text-secondary',
                'action' => '/post-lead-form',
                'method' => 'POST',
                'id' => 'demand-generation-lead-form',
                'class' => 'ajaxForm',
                'attributes' => [
                    'data-meta-form-name' => 'demand-generation-form',
                    'data-meta-success-event' => 'Lead',
                ],
                'fields' => [
                    [
                        'type' => 'text',
                        'name' => 'name',
                        'id' => 'name',
                        'label' => 'Name',
                        'required' => true,
                        'autocomplete' => 'name',
                        'wrapperClass' => 'mb-3',
                        'labelClass' => 'form-label fw-semibold',
                        'inputClass' => 'form-control',
                    ],
                    [
                        'type' => 'email',
                        'name' => 'email',
                        'id' => 'email',
                        'label' => 'Email',
                        'required' => true,
                        'autocomplete' => 'email',
                        'wrapperClass' => 'mb-3',
                        'labelClass' => 'form-label fw-semibold',
                        'inputClass' => 'form-control',
                    ],
                    [
                        'type' => 'tel',
                        'name' => 'phone',
                        'id' => 'phone',
                        'label' => 'Phone',
                        'labelSuffix' => '(optional)',
                        'required' => false,
                        'autocomplete' => 'tel',
                        'wrapperClass' => 'col-sm-6',
                        'labelClass' => 'form-label fw-semibold',
                        'labelSuffixClass' => 'fw-normal text-secondary',
                        'inputClass' => 'form-control',
                        'group' => 'contact-details',
                    ],
                    [
                        'type' => 'select',
                        'name' => 'monthly_marketing_spend',
                        'id' => 'monthly-marketing-spend',
                        'label' => 'Monthly marketing spend',
                        'required' => false,
                        'wrapperClass' => 'col-sm-6',
                        'labelClass' => 'form-label fw-semibold',
                        'inputClass' => 'form-select',
                        'group' => 'contact-details',
                        'options' => [
                            [
                                'label' => 'Select',
                                'value' => '',
                            ],
                            [
                                'label' => 'Not currently spending',
                                'value' => 'none',
                            ],
                            [
                                'label' => 'Under $2,500',
                                'value' => 'under-2500',
                            ],
                            [
                                'label' => '$2,500-$5,000',
                                'value' => '2500-5000',
                            ],
                            [
                                'label' => '$5,000-$10,000',
                                'value' => '5000-10000',
                            ],
                            [
                                'label' => '$10,000+',
                                'value' => '10000-plus',
                            ],
                        ],
                    ],
                    [
                        'type' => 'textarea',
                        'name' => 'comment',
                        'id' => 'comment',
                        'label' => 'What is not working today?',
                        'placeholder' => 'Tell us about your traffic, lead quality, conversion rate, or follow-up...',
                        'required' => false,
                        'rows' => 4,
                        'wrapperClass' => 'mb-4',
                        'labelClass' => 'form-label fw-semibold',
                        'inputClass' => 'form-control',
                    ],
                    [
                        'type' => 'hidden',
                        'name' => 'interests[]',
                        'value' => 'demand-generation',
                    ],
                ],
                'fieldGroups' => [
                    'contact-details' => 'row g-3 mb-3',
                ],
                'submit' => [
                    'label' => 'Request My Free Demand Review',
                    'class' => 'btn btn-skale btn-lg w-100',
                ],
                'privacy' => [
                    'text' => 'No sales pressure. Your information stays private.',
                    'class' => 'small text-secondary text-center mt-3 mb-0',
                    'iconClass' => 'fa-solid fa-lock me-1',
                ],
            ],
        ],
        
        'trustStrip' => [
            'enabled' => true,
            'id' => 'trust-strip',
            'tag' => 'section',
            'class' => 'trust-strip trust-strip-demand',
            'containerClass' => 'container',
            'rowClass' => 'row row-cols-2 row-cols-lg-4 g-3',
            'columnClass' => 'col',
            'itemClass' => 'trust-item',
            'ariaLabel' => 'Why businesses trust Skale for demand generation',
            'items' => [
                [
                    'iconClass' => 'bi bi-bullseye',
                    'title' => 'Qualified Demand',
                    'description' => 'Focus on buyers who are more likely to convert',
                ],
                [
                    'iconClass' => 'bi bi-diagram-3',
                    'title' => 'Connected Channels',
                    'description' => 'SEO, paid media, email, and landing pages work together',
                ],
                [
                    'iconClass' => 'bi bi-graph-up-arrow',
                    'title' => 'Revenue Visibility',
                    'description' => 'Measure performance beyond clicks and impressions',
                ],
                [
                    'iconClass' => 'bi bi-person-check',
                    'title' => 'Senior Strategy',
                    'description' => 'Direct guidance from an experienced growth partner',
                ],
            ],
        ],

        'problems' => [
            'enabled' => true,
            'id' => 'problems',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'introClass' => 'section-intro',
            'eyebrow' => 'Why Marketing Stalls',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'More traffic will not fix a disconnected acquisition system.',
            'headingTag' => 'h2',
            'description' => 'Many businesses are active across several channels but still struggle to create dependable pipeline. The problem is usually not effort. It is weak alignment between audience, message, offer, landing experience, follow-up, and measurement.',
            'descriptionClass' => 'mt-3',
            'rowClass' => 'row g-4',
            'columnClass' => 'col-md-6 col-xl-3',
            'cardClass' => 'problem-card h-100',
            'iconWrapperClass' => 'icon-box icon-box-accent',
            'titleClass' => 'h5',
            'bodyClass' => 'mb-0',
            'items' => [
                [
                    'iconClass' => 'bi bi-megaphone',
                    'title' => 'You attract the wrong traffic',
                    'description' => 'Campaigns generate visits, but too few visitors match your ideal customer or have meaningful intent.',
                ],
                [
                    'iconClass' => 'bi bi-signpost-split',
                    'title' => 'The message changes by channel',
                    'description' => 'Ads, search listings, emails, and landing pages make different promises and create confusion.',
                ],
                [
                    'iconClass' => 'bi bi-hourglass-split',
                    'title' => 'Follow-up happens too slowly',
                    'description' => 'Interested prospects wait, receive generic outreach, or disappear before a real conversation begins.',
                ],
                [
                    'iconClass' => 'bi bi-bar-chart',
                    'title' => 'Reporting stops at clicks',
                    'description' => 'You can see activity, but not which channels, offers, and campaigns produce qualified opportunities.',
                ],
            ],
        ],

        'outcomes' => [
            'enabled' => true,
            'id' => 'outcomes',
            'tag' => 'section',
            'class' => 'section-space pt-0',
            'containerClass' => 'container',
            'panelClass' => 'outcome-panel outcome-panel-demand',
            'rowClass' => 'row align-items-center g-5',
            'contentColumnClass' => 'col-lg-5',
            'listColumnClass' => 'col-lg-7',
            'eyebrow' => 'The Outcome',
            'eyebrowClass' => 'eyebrow text-white-50',
            'heading' => 'A demand engine that creates momentum before the sales call.',
            'headingTag' => 'h2',
            'description' => 'Skale builds a connected path from discovery to conversion so each channel supports the same audience, message, offer, and business goal.',
            'descriptionClass' => 'mt-3 mb-0 text-white-75',
            'listClass' => 'outcome-list',
            'iconClass' => 'bi bi-check-circle-fill',
            'items' => [
                [
                    'title' => 'Reach people with real buying intent',
                    'description' => 'Use search behavior, audience signals, and focused targeting to prioritize quality over volume.',
                ],
                [
                    'title' => 'Create a consistent reason to act',
                    'description' => 'Align ads, content, landing pages, and offers around the problems your customers already want solved.',
                ],
                [
                    'title' => 'Convert more attention into conversations',
                    'description' => 'Improve pages, forms, calls to action, and follow-up so qualified interest does not go to waste.',
                ],
                [
                    'title' => 'Know what is creating pipeline',
                    'description' => 'Connect campaign data, analytics, and lead tracking to the outcomes that matter to your business.',
                ],
            ],
        ],

        'serviceComponents' => [
            'enabled' => true,
            'id' => 'demand-generation-services',
            'tag' => 'section',
            'class' => 'section-space bg-soft',
            'containerClass' => 'container',
            'headerRowClass' => 'row align-items-end mb-5 g-3',
            'headingColumnClass' => 'col-lg-8',
            'descriptionColumnClass' => 'col-lg-4',
            'eyebrow' => 'What We Build',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'The connected components of a modern demand generation system.',
            'headingTag' => 'h2',
            'headingClass' => 'mb-0',
            'description' => 'Your engagement can focus on one immediate constraint or combine several channels into a coordinated acquisition program.',
            'descriptionClass' => 'mb-0',
            'rowClass' => 'row g-4',
            'columnClass' => 'col-md-6 col-xl-4',
            'cardClass' => 'service-card service-card-demand h-100',
            'numberClass' => 'service-number',
            'iconWrapperClass' => 'icon-box icon-box-accent',
            'titleClass' => 'h4',
            'listClass' => 'service-list',
            'listIconClass' => 'bi bi-check2',
            'items' => [
                [
                    'iconClass' => 'bi bi-search',
                    'title' => 'SEO & Content Strategy',
                    'description' => 'Build durable visibility around the questions, problems, and services your ideal customers are actively searching for.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/search-engine-optimization',
                    'bullets' => [
                        'Keyword and opportunity research',
                        'Technical and on-page SEO',
                        'Service pages and conversion-focused content',
                    ],
                ],
                [
                    'iconClass' => 'bi bi-google',
                    'title' => 'Paid Search',
                    'description' => 'Capture high-intent demand with focused Google Ads campaigns built around qualified actions rather than cheap clicks.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/ppc-solutions',
                    'bullets' => [
                        'Campaign and account structure',
                        'Keyword, audience, and negative targeting',
                        'Ad copy, landing pages, and conversion tracking',
                    ],
                ],
                [
                    'iconClass' => 'bi bi-meta',
                    'title' => 'Paid Social',
                    'description' => 'Create demand and retarget engaged prospects with Meta campaigns that connect audience, creative, offer, and landing experience.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/ppc-solutions',
                    'bullets' => [
                        'Audience and campaign strategy',
                        'Creative and message testing',
                        'Retargeting and lead-generation funnels',
                    ],
                ],
                [
                    'iconClass' => 'bi bi-envelope-paper',
                    'title' => 'Email Marketing & Nurturing',
                    'description' => 'Stay relevant after the first interaction with campaigns and automated sequences that educate, qualify, and re-engage.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/email-marketing',
                    'bullets' => [
                        'Lead nurture sequences',
                        'Newsletter and campaign strategy',
                        'Segmentation and behavior-based automation',
                    ],
                ],
                [
                    'iconClass' => 'bi bi-window',
                    'title' => 'Landing Pages & Conversion',
                    'description' => 'Turn campaign traffic into action with focused pages that make the next step clear, credible, and easy to complete.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/conversion-optimization',
                    'bullets' => [
                        'Campaign landing pages',
                        'Messaging and offer refinement',
                        'Forms, calls to action, and conversion testing',
                    ],
                ],
                [
                    'iconClass' => 'bi bi-clipboard-data',
                    'title' => 'Analytics & Attribution',
                    'description' => 'Create a reliable view of what happens after the click and which efforts are contributing to qualified pipeline.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/marketing-analytics',
                    'bullets' => [
                        'Analytics and event tracking',
                        'Campaign dashboards and reporting',
                        'Lead-source and conversion analysis',
                    ],
                ],
            ],
            'cta' => [
                'label' => 'Talk Through Your Demand Gaps',
                'url' => '#consultation',
                'wrapperClass' => 'text-center mt-5',
                'class' => 'btn btn-accent btn-lg',
            ],
        ],

        // 'services' => [
        //     'enabled' => false,
        //     'id' => 'related-services',
        //     'tag' => 'section',
        //     'class' => 'section-space',
        //     'containerClass' => 'container',
        //     'items' => [],
        // ],

        'caseStudy' => [
            'enabled' => true,
            'id' => 'case-study',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'panelClass' => 'case-study case-study-demand',
            'rowClass' => 'row align-items-center g-5',
            'contentColumnClass' => 'col-lg-6',
            'metricsColumnClass' => 'col-lg-6',
            'label' => 'Connected Campaign Example',
            'labelClass' => 'case-label',
            'heading' => 'From isolated campaigns to one measurable customer journey.',
            'headingTag' => 'h2',
            'headingClass' => 'mt-2',
            'description' => 'A service business was driving traffic through paid ads while managing follow-up manually and evaluating success through platform-level metrics. The opportunity was not simply to spend more. It was to connect the campaign message, landing page, lead capture, response process, and reporting.',
            'descriptionClass' => 'mt-3',
            'lessonLabel' => 'The lesson:',
            'lesson' => 'Demand generation improves when every step—from first impression to sales follow-up—is designed as one system.',
            'lessonClass' => 'mb-0',
            'metricsRowClass' => 'row g-3',
            'metricColumnClass' => 'col-6',
            'metricClass' => 'metric metric-accent h-100',
            'metrics' => [
                [
                    'value' => 'Clearer',
                    'label' => 'Visibility into lead sources',
                ],
                [
                    'value' => 'Faster',
                    'label' => 'Response and follow-up',
                ],
                [
                    'value' => 'Stronger',
                    'label' => 'Message-to-page alignment',
                ],
                [
                    'value' => 'Focused',
                    'label' => 'Optimization around qualified leads',
                ],
            ],
            'disclaimer' => 'Replace this representative example with verified client metrics, a named case study, or a testimonial when available.',
            'disclaimerClass' => 'small mt-3 mb-0 text-secondary',
        ],

        'process' => [
            'enabled' => true,
            'id' => 'how-it-works',
            'tag' => 'section',
            'class' => 'section-space bg-soft',
            'containerClass' => 'container',
            'introClass' => 'section-intro',
            'eyebrow' => 'How It Works',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'Build demand by fixing the system in the right order.',
            'headingTag' => 'h2',
            'description' => 'We begin with the business outcome, identify the biggest constraint, and improve the customer journey before scaling activity.',
            'descriptionClass' => 'mt-3',
            'rowClass' => 'row g-4',
            'columnClass' => 'col-md-6 col-xl-3',
            'cardClass' => 'process-card process-card-demand h-100',
            'stepClass' => 'process-step',
            'titleClass' => 'h5',
            'bodyClass' => 'mb-0',
            'items' => [
                [
                    'step' => '1',
                    'title' => 'Diagnose',
                    'description' => 'Review your audience, channels, offers, landing pages, follow-up, analytics, and current sources of pipeline.',
                ],
                [
                    'step' => '2',
                    'title' => 'Prioritize',
                    'description' => 'Identify the highest-impact gap and establish clear goals, conversion actions, and success measures.',
                ],
                [
                    'step' => '3',
                    'title' => 'Build & Launch',
                    'description' => 'Create or improve campaigns, content, landing pages, tracking, nurture, and lead-management workflows.',
                ],
                [
                    'step' => '4',
                    'title' => 'Measure & Scale',
                    'description' => 'Use real performance data to improve quality, conversion, cost efficiency, and investment decisions.',
                ],
            ],
        ],

        'founder' => [
            'enabled' => true,
            'id' => 'founder',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'panelClass' => 'founder-panel',
            'rowClass' => 'row align-items-center g-4',
            'avatarColumnClass' => 'col-lg-auto',
            'contentColumnClass' => 'col-lg',
            'ctaColumnClass' => 'col-lg-auto',
            'avatar' => [
                'type' => 'initials',
                'value' => 'JB',
                'image' => null,
                'alt' => 'Joe Brown',
                'class' => 'founder-avatar founder-avatar-accent',
            ],
            'quoteMark' => '“',
            'quoteMarkClass' => 'quote-mark',
            'heading' => 'Your marketing strategy should not be separated from your technology and sales process.',
            'headingTag' => 'h2',
            'headingClass' => 'h3',
            'description' => 'Skale is led by Joe Brown, a technology and growth partner with more than 20 years of experience across websites, software, analytics, automation, and digital marketing.',
            'descriptionClass' => 'mb-2',
            'emphasis' => 'You receive senior-level guidance that connects acquisition decisions to the systems responsible for capturing, following up with, and measuring every opportunity.',
            'emphasisClass' => 'mb-0 text-dark',
            'cta' => [
                'label' => 'Learn About Skale',
                'url' => '/about',
                'class' => 'btn btn-outline-dark',
            ],
        ],

        'qualification' => [
            'enabled' => true,
            'id' => 'qualification',
            'tag' => 'section',
            'class' => 'section-space pt-0',
            'containerClass' => 'container',
            'rowClass' => 'row g-5 align-items-center',
            'headingColumnClass' => 'col-lg-6',
            'itemsColumnClass' => 'col-lg-6',
            'itemsRowClass' => 'row g-3',
            'itemColumnClass' => 'col-12',
            'itemClass' => 'd-flex gap-3 p-3 border rounded-4 h-100 qualification-item-demand',
            'eyebrow' => 'Who This Is For',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'A strong fit for businesses ready to turn scattered marketing into a measurable growth system.',
            'headingTag' => 'h2',
            'iconClass' => 'bi bi-check-circle-fill text-accent fs-5',
            'titleClass' => 'd-block',
            'descriptionClass' => 'text-secondary',
            'items' => [
                [
                    'title' => 'You are getting traffic but not enough qualified leads.',
                    'description' => 'Your channels create activity, but the path from click to conversation is inconsistent.',
                ],
                [
                    'title' => 'You are running marketing without reliable attribution.',
                    'description' => 'You cannot confidently explain which campaigns, pages, or sources contribute to pipeline.',
                ],
                [
                    'title' => 'You need strategy and execution connected.',
                    'description' => 'You want one partner who can improve the message, campaigns, pages, tracking, and supporting systems.',
                ],
                [
                    'title' => 'You are prepared to improve before increasing spend.',
                    'description' => 'You value fixing conversion and follow-up gaps instead of simply buying more traffic.',
                ],
            ],
        ],

        'faq' => [
            'enabled' => true,
            'id' => 'faq',
            'tag' => 'section',
            'class' => 'section-space bg-soft',
            'containerClass' => 'container',
            'rowClass' => 'row g-5',
            'introColumnClass' => 'col-lg-5',
            'accordionColumnClass' => 'col-lg-7',
            'eyebrow' => 'Common Questions',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'What businesses usually want to know before investing in demand generation.',
            'headingTag' => 'h2',
            'description' => 'The first conversation is designed to understand your current acquisition system, identify the most important constraint, and determine whether Skale is the right fit.',
            'descriptionClass' => 'mt-3',
            'accordionId' => 'demandGenerationFaq',
            'accordionClass' => 'accordion accordion-demand',
            'itemClass' => 'accordion-item',
            'headerClass' => 'accordion-header',
            'buttonClass' => 'accordion-button',
            'collapsedButtonClass' => 'accordion-button collapsed',
            'collapseClass' => 'accordion-collapse collapse',
            'openCollapseClass' => 'accordion-collapse collapse show',
            'bodyClass' => 'accordion-body',
            'allowMultipleOpen' => false,
            'items' => [
                [
                    'id' => 'faq-demand-generation',
                    'question' => 'What is demand generation?',
                    'answer' => 'Demand generation is the connected process of creating awareness, attracting the right audience, building trust, capturing interest, nurturing prospects, and turning qualified demand into sales opportunities. It can include SEO, paid media, content, email, landing pages, conversion optimization, analytics, and lead-management workflows.',
                    'open' => true,
                ],
                [
                    'id' => 'faq-channels',
                    'question' => 'Do we need to use every marketing channel?',
                    'answer' => 'No. The right channel mix depends on your audience, offer, sales cycle, budget, existing visibility, and current constraints. It is usually better to operate a smaller number of connected channels well than to spread resources across every available platform.',
                    'open' => false,
                ],
                [
                    'id' => 'faq-existing-campaigns',
                    'question' => 'Can you improve campaigns we already have?',
                    'answer' => 'Yes. Skale can review existing SEO, Google Ads, Meta campaigns, email programs, landing pages, analytics, and follow-up processes. In many cases, the fastest opportunity comes from improving the existing system before launching something new.',
                    'open' => false,
                ],
                [
                    'id' => 'faq-budget',
                    'question' => 'How much should we spend on paid advertising?',
                    'answer' => 'There is no universal amount. Budget should reflect your economics, market, conversion path, sales capacity, and the amount of data needed to make informed decisions. We first make sure the strategy, offer, tracking, and landing experience are strong enough to support paid traffic.',
                    'open' => false,
                ],
                [
                    'id' => 'faq-success',
                    'question' => 'How do you measure success?',
                    'answer' => 'Success measures are defined around your business goals. Depending on the engagement, they may include qualified leads, booked consultations, conversion rate, lead quality, cost per qualified opportunity, organic visibility, email engagement, pipeline contribution, and revenue attribution.',
                    'open' => false,
                ],
                [
                    'id' => 'faq-timeline',
                    'question' => 'How quickly can we expect results?',
                    'answer' => 'Paid campaigns and conversion improvements can generate useful data relatively quickly, while SEO and content typically build momentum over a longer period. The timeline depends on your starting point, market, budget, sales cycle, and the amount of infrastructure that needs to be improved.',
                    'open' => false,
                ],
            ],
        ],

        'finalCta' => [
            'enabled' => true,
            'id' => 'final-cta',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'panelClass' => 'final-cta final-cta-demand text-center',
            'rowClass' => 'row justify-content-center',
            'columnClass' => 'col-lg-9',
            'badge' => 'Build demand with clarity',
            'badgeClass' => 'badge rounded-pill bg-accent-subtle text-accent-emphasis mb-3',
            'heading' => 'Find out why your marketing is creating activity—but not enough pipeline.',
            'headingTag' => 'h2',
            'description' => 'Schedule a free demand review to talk through your audience, channels, conversion path, follow-up, and the most valuable place to improve first.',
            'descriptionClass' => 'lead mt-3 mb-4',
            'buttons' => [
                'wrapperClass' => 'd-flex flex-column flex-sm-row justify-content-center gap-3',
                'items' => [
                    [
                        'label' => 'Book My Free Demand Review',
                        'url' => '#consultation',
                        'class' => 'btn btn-accent btn-lg',
                        'iconClass' => null,
                    ],
                    [
                        'label' => '732-925-4044',
                        'url' => 'tel:+17329254044',
                        'class' => 'btn btn-outline-light btn-lg',
                        'iconClass' => 'bi bi-telephone me-2',
                    ],
                ],
            ],
            'note' => 'No obligation. No prebuilt package. A practical conversation focused on your current growth system.',
            'noteClass' => 'small mt-3 mb-0',
        ],
    ],
];
