<?php

declare(strict_types=1);

return [
    // 'name' => 'Strategy & Optimization',
    // 'slug' => 'strategy-and-optimization',

    // 'seo' => [
    //     'title' => 'Strategy & Optimization Services | Skale',
    //     'description' => 'Identify growth constraints, simplify technology, improve performance tracking, and create a prioritized roadmap for smarter business decisions.',
    //     'canonical' => '/solutions/strategy-and-optimization',
    //     'robots' => 'index,follow',
    //     'ogType' => 'website',
    //     'ogImage' => null,
    // ],

    'sections' => [
        'hero' => [
            'enabled' => true,
            'id' => 'strategy-and-optimization-hero',
            'tag' => 'section',
            'class' => 'hero hero-strategy-optimization position-relative overflow-hidden text-white',
            'containerClass' => 'container position-relative',
            'rowClass' => 'row align-items-center g-5',
            'contentColumnClass' => 'col-lg-7',
            'formColumnClass' => 'col-lg-5',
            'contentClass' => 'hero-copy',
            'eyebrow' => 'Strategy & Optimization',
            'eyebrowClass' => 'eyebrow eyebrow-light',
            'heading' => 'Stop guessing what to fix next. Build a clear plan to',
            'highlight' => 'improve performance.',
            'headingTag' => 'h1',
            'headingClass' => '',
            'highlightClass' => 'text-highlight text-amber',
            'description' => 'Skale evaluates the systems behind your growth, identifies the highest-impact constraints, and creates a practical roadmap to improve technology, marketing, operations, and measurement.',
            'descriptionClass' => 'hero-lead mt-4 mb-0 text-white-75',
            'background' => [
                'class' => 'hero-strategy-optimization-bg',
                'overlayClass' => 'hero-strategy-optimization-overlay',
                'decorations' => [
                    ['class' => 'hero-strategy-grid', 'ariaHidden' => true],
                    ['class' => 'hero-strategy-orb hero-strategy-orb-one', 'ariaHidden' => true],
                    ['class' => 'hero-strategy-orb hero-strategy-orb-two', 'ariaHidden' => true],
                ],
            ],
            'benefits' => [
                'class' => 'hero-checks hero-checks-light',
                'ariaLabel' => 'Key benefits',
                'iconClass' => 'bi bi-check-circle-fill text-amber',
                'items' => [
                    'Clear priorities instead of scattered initiatives',
                    'Recommendations tied to measurable business outcomes',
                    'Senior guidance across technology, marketing, and operations',
                ],
            ],
            'buttons' => [
                'wrapperClass' => 'd-flex flex-column flex-sm-row gap-3',
                'items' => [
                    [
                        'label' => 'Get Your Free Growth Audit',
                        'url' => '#consultation',
                        'class' => 'btn btn-primary btn-lg',
                        'target' => null,
                        'rel' => null,
                    ],
                    [
                        'label' => 'See How It Works',
                        'url' => '#how-it-works',
                        'class' => 'btn btn-outline-dark btn-lg',
                        'target' => null,
                        'rel' => null,
                    ],
                ],
            ],
            'note' => [
                'text' => 'No pressure. No generic sales pitch. Just a practical conversation about what is holding your business back.',
                'class' => 'hero-note hero-note-light',
                'iconClass' => 'bi bi-shield-check',
            ],
            'form' => [
                'enabled' => true,
                'anchorId' => 'consultation',
                'wrapperClass' => 'hero-form-wrap',
                'cardClass' => 'lead-form-card lead-form-card-strategy',
                'headerClass' => 'mb-4',
                'badge' => 'Free 30-minute consultation',
                'badgeClass' => 'badge text-bg-light border mb-3',
                'heading' => 'Find the biggest constraint on your growth',
                'headingTag' => 'h2',
                'headingClass' => 'h3 mb-2',
                'description' => 'Tell us what feels unclear, inefficient, or underperforming. We will help identify where better strategy, systems, or measurement could make the greatest difference.',
                'descriptionClass' => 'mb-0',
                'action' => '/post-lead-form',
                'method' => 'POST',
                'id' => 'strategy-optimization-form',
                'class' => 'ajaxForm',
                'attributes' => [
                    'dataMetaFormName' => 'strategy-and-optimization-form',
                    'dataMetaSuccessEvent' => 'Lead',
                ],
                'fields' => [
                    [
                        'type' => 'text',
                        'name' => 'name',
                        'id' => 'name',
                        'label' => 'Name',
                        'required' => true,
                        'autocomplete' => 'name',
                        'wrapperClass' => 'mb-3',
                        'labelClass' => 'form-label fw-semibold',
                        'inputClass' => 'form-control',
                    ],
                    [
                        'type' => 'email',
                        'name' => 'email',
                        'id' => 'email',
                        'label' => 'Email',
                        'required' => true,
                        'autocomplete' => 'email',
                        'wrapperClass' => 'mb-3',
                        'labelClass' => 'form-label fw-semibold',
                        'inputClass' => 'form-control',
                    ],
                    [
                        'type' => 'tel',
                        'name' => 'phone',
                        'id' => 'phone',
                        'label' => 'Phone',
                        'labelSuffix' => '(optional)',
                        'required' => false,
                        'autocomplete' => 'tel',
                        'wrapperClass' => 'col-sm-6',
                        'labelClass' => 'form-label fw-semibold',
                        'labelSuffixClass' => 'fw-normal text-secondary',
                        'inputClass' => 'form-control',
                        'group' => 'contact-details',
                    ],
                    [
                        'type' => 'select',
                        'name' => 'team_size',
                        'id' => 'team',
                        'label' => 'Team size',
                        'required' => false,
                        'wrapperClass' => 'col-sm-6',
                        'labelClass' => 'form-label fw-semibold',
                        'inputClass' => 'form-select',
                        'group' => 'contact-details',
                        'options' => [
                            ['label' => 'Select', 'value' => ''],
                            ['label' => 'Just me', 'value' => 'Just me'],
                            ['label' => '2-5 people', 'value' => '2-5 people'],
                            ['label' => '6-15 people', 'value' => '6-15 people'],
                            ['label' => '16-50 people', 'value' => '16-50 people'],
                            ['label' => '50+ people', 'value' => '50+ people'],
                        ],
                    ],
                    [
                        'type' => 'textarea',
                        'name' => 'comment',
                        'id' => 'comment',
                        'label' => 'What is your biggest challenge?',
                        'placeholder' => 'Tell us what you want to improve...',
                        'required' => false,
                        'rows' => 4,
                        'wrapperClass' => 'mb-4',
                        'labelClass' => 'form-label fw-semibold',
                        'inputClass' => 'form-control',
                    ],
                    [
                        'type' => 'hidden',
                        'name' => 'interests[]',
                        'value' => 'strategy-and-optimization',
                    ],
                ],
                'fieldGroups' => [
                    'contact-details' => 'row g-3 mb-3',
                ],
                'submit' => [
                    'label' => 'Request My Free Growth Audit',
                    'class' => 'btn btn-skale btn-lg w-100',
                ],
                'privacy' => [
                    'text' => 'No sales pressure. Your information stays private.',
                    'class' => 'small text-secondary text-center mt-3 mb-0',
                    'iconClass' => 'fa-solid fa-lock me-1',
                ],
            ],
        ],

        'trustStrip' => [
            'enabled' => true,
            'id' => 'trust-strip',
            'tag' => 'section',
            'class' => 'trust-strip trust-strip-strategy',
            'containerClass' => 'container',
            'rowClass' => 'row row-cols-2 row-cols-lg-4 g-3',
            'columnClass' => 'col',
            'itemClass' => 'trust-item',
            'ariaLabel' => 'Why businesses trust Skale',
            'items' => [
                [
                    'iconClass' => 'bi bi-person-check',
                    'title' => 'Senior Expertise',
                    'description' => 'Direct access to an experienced partner',
                ],
                [
                    'iconClass' => 'bi bi-diagram-3',
                    'title' => 'Systems Thinking',
                    'description' => 'Every tool supports a larger strategy',
                ],
                [
                    'iconClass' => 'bi bi-graph-up-arrow',
                    'title' => 'Outcome Focused',
                    'description' => 'Decisions tied to measurable progress',
                ],
                [
                    'iconClass' => 'bi bi-headset',
                    'title' => 'Ongoing Support',
                    'description' => 'A long-term partner after launch',
                ],
            ],
        ],

        'problems' => [
            'enabled' => true,
            'id' => 'problems',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'introClass' => 'section-intro',
            'eyebrow' => 'Why Progress Stalls',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'Businesses rarely lack ideas. They lack clarity about which idea matters most.',
            'headingTag' => 'h2',
            'description' => 'When priorities, technology, marketing, operations, and reporting are evaluated separately, teams stay busy without knowing whether their work is solving the right problem.',
            'descriptionClass' => 'mt-3',
            'rowClass' => 'row g-4',
            'columnClass' => 'col-md-6 col-xl-3',
            'cardClass' => 'problem-card problem-card-strategy h-100',
            'iconWrapperClass' => 'icon-box icon-box-amber',
            'titleClass' => 'h5',
            'bodyClass' => 'mb-0',
            'items' => [
                [
                    'iconClass' => 'bi bi-funnel',
                    'title' => 'Too many competing priorities',
                    'description' => 'Every initiative appears important, so resources are spread across projects without a clear sequence or expected return.',
                ],
                [
                    'iconClass' => 'bi bi-arrows-angle-contract',
                    'title' => 'Technology has accumulated',
                    'description' => 'Tools, subscriptions, integrations, and workarounds grow over time without a shared architecture or ownership plan.',
                ],
                [
                    'iconClass' => 'bi bi-plug',
                    'title' => 'Performance is difficult to explain',
                    'description' => 'Reports show activity, but leaders cannot easily connect marketing, technology, or operational work to business results.',
                ],
                [
                    'iconClass' => 'bi bi-bar-chart-line',
                    'title' => 'Teams keep reacting',
                    'description' => 'Decisions are driven by immediate problems instead of a prioritized plan for improving the underlying system.',
                ],
            ],
        ],

        'outcomes' => [
            'enabled' => true,
            'id' => 'outcomes',
            'tag' => 'section',
            'class' => 'section-space pt-0',
            'containerClass' => 'container',
            'panelClass' => 'outcome-panel outcome-panel-strategy',
            'rowClass' => 'row align-items-center g-5',
            'contentColumnClass' => 'col-lg-5',
            'itemsColumnClass' => 'col-lg-7',
            'eyebrow' => 'The Outcome',
            'eyebrowClass' => 'eyebrow text-white',
            'heading' => 'A clear operating roadmap for what to improve, why it matters, and what should happen next.',
            'headingTag' => 'h2',
            'description' => 'Skale turns scattered concerns and disconnected data into a practical sequence of decisions, improvements, and measurable priorities.',
            'descriptionClass' => 'mt-3 mb-0',
            'listClass' => 'outcome-list',
            'iconClass' => 'bi bi-check-circle-fill',
            'items' => [
                [
                    'title' => 'Know where to focus first',
                    'description' => 'Rank opportunities by business impact, urgency, effort, dependency, and risk.',
                ],
                [
                    'title' => 'Simplify the systems behind the work',
                    'description' => 'Identify unnecessary tools, duplicated capabilities, weak integrations, and avoidable complexity.',
                ],
                [
                    'title' => 'Measure what drives decisions',
                    'description' => 'Create reporting that connects activity to conversion, efficiency, customer experience, and financial outcomes.',
                ],
                [
                    'title' => 'Improve continuously instead of starting over',
                    'description' => 'Establish a repeatable optimization process based on evidence, learning, and changing business priorities.',
                ],
            ],
        ],

        'serviceComponents' => [
            'enabled' => true,
            'id' => 'service-components',
            'tag' => 'section',
            'class' => 'section-space bg-soft',
            'containerClass' => 'container',
            'headerRowClass' => 'row align-items-end mb-5 g-3',
            'headingColumnClass' => 'col-lg-8',
            'descriptionColumnClass' => 'col-lg-4',
            'eyebrow' => 'What We Evaluate',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'The decisions and systems that shape business performance.',
            'headingTag' => 'h2',
            'headingClass' => 'mb-0',
            'description' => 'Your engagement can address one urgent decision or provide a broader assessment of the systems supporting growth.',
            'descriptionClass' => 'mb-0',
            'rowClass' => 'row g-4',
            'columnClass' => 'col-md-6 col-xl-4',
            'cardClass' => 'service-card service-card-strategy h-100',
            'numberClass' => 'service-number',
            'iconWrapperClass' => 'icon-box icon-box-amber',
            'titleClass' => 'h4',
            'listIconClass' => 'bi bi-check2',
            'items' => [
                [
                    'iconClass' => 'bi bi-window',
                    'title' => 'Growth Audits',
                    'description' => 'Evaluate where your business is losing leads, time, visibility, efficiency, or momentum.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/growth-infrastructure',
                    'bullets' => [
                        'Customer journey and conversion review',
                        'Operational and workflow assessment',
                        'Prioritized findings and recommendations',
                    ],
                ],
                [
                    'iconClass' => 'bi bi-megaphone',
                    'title' => 'System Mapping & Roadmaps',
                    'description' => 'Create a shared view of the systems, data, teams, and dependencies behind an important business process.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/strategy-and-optimization',
                    'bullets' => [
                        'Current-state system mapping',
                        'Future-state architecture and workflows',
                        'Phased implementation roadmap',
                    ],
                ],
                [
                    'iconClass' => 'bi bi-people',
                    'title' => 'Technology Stack Optimization',
                    'description' => 'Simplify the tools your business uses and ensure each platform supports a clear operational purpose.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/it-solutions',
                    'bullets' => [
                        'Platform and subscription evaluation',
                        'Integration and data-flow review',
                        'Consolidation and modernization planning',
                    ],
                ],
                [
                    'iconClass' => 'bi bi-lightning-charge',
                    'title' => 'System Mapping & Roadmaps Automation',
                    'description' => 'Build a reliable measurement system that helps leaders understand performance and make better decisions.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/strategy-and-optimization',
                    'bullets' => [
                        'System Mapping & Roadmaps and sales automation',
                        'Monthly or quarterly performance reviews and validation',
                        'Dashboards and executive reporting',
                    ],
                ],
                [
                    'iconClass' => 'bi bi-link-45deg',
                    'title' => 'Conversion Optimization',
                    'description' => 'Identify where prospects abandon the journey and improve the experiences responsible for generating action.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/conversion-optimization',
                    'bullets' => [
                        'Funnel and landing-page analysis',
                        'Messaging, offer, and CTA review',
                        'Testing and improvement roadmap',
                    ],
                ],
                [
                    'iconClass' => 'bi bi-clipboard-data',
                    'title' => 'System Mapping & Roadmaps Analytics',
                    'description' => 'Create a disciplined cadence for reviewing performance, prioritizing improvements, and adapting the system.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/strategy-and-optimization',
                    'bullets' => [
                        'Monthly or quarterly performance reviews',
                        'Experiment and improvement planning',
                        'Strategic guidance as priorities change',
                    ],
                ],
            ],
            'cta' => [
                'wrapperClass' => 'text-center mt-5',
                'label' => 'Talk Through Your Priorities',
                'url' => '#consultation',
                'class' => 'btn btn-amber btn-lg',
            ],
        ],

        // Reserved for a separate related-services or individual-service listing component.
        // The source HTML does not contain an additional services section beyond serviceComponents.
        // 'services' => [
        //     'enabled' => false,
        //     'id' => 'services',
        //     'tag' => 'section',
        //     'class' => 'section-space',
        //     'containerClass' => 'container',
        //     'eyebrow' => '',
        //     'heading' => '',
        //     'description' => '',
        //     'rowClass' => 'row g-4',
        //     'columnClass' => 'col-md-6 col-xl-4',
        //     'cardClass' => 'service-card h-100',
        //     'items' => [],
        // ],

        'caseStudy' => [
            'enabled' => true,
            'id' => 'case-study',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'panelClass' => 'case-study case-study-strategy',
            'rowClass' => 'row align-items-center g-5',
            'contentColumnClass' => 'col-lg-6',
            'metricsColumnClass' => 'col-lg-6',
            'label' => 'Client Transformation',
            'labelClass' => 'case-label',
            'heading' => 'From an expensive, fragmented platform to a clearer and more scalable operating model.',
            'headingTag' => 'h2',
            'headingClass' => 'mt-2',
            'description' => 'A growing product-data organization was constrained by disconnected tools, slow publishing, rising operating costs, and a platform that could not support its expanding data volume. The work began by understanding the entire system not by replacing one isolated component. Skale helped reposition the architecture, simplify the workflow, and create a roadmap for a unified platform serving multiple products and delivery channels.',
            'descriptionClass' => 'mt-3',
            'lessonLabel' => 'The lesson:',
            'lesson' => 'The highest-value strategy often comes from identifying the system behind several visible problems and solving those problems in the right sequence.',
            'lessonClass' => 'mb-0',
            'lessonLabelClass' => 'text-dark',
            'metricsRowClass' => 'row g-3',
            'metricColumnClass' => 'col-6',
            'metricClass' => 'metric metric-amber h-100',
            'metrics' => [
                ['value' => '50%+', 'label' => 'Reduction in operating costs'],
                ['value' => '1M+', 'label' => 'Records supported at scale'],
                ['value' => 'Faster', 'label' => 'Publishing and delivery workflows'],
                ['value' => 'Unified', 'label' => 'Data, systems, and processes'],
            ],
            'disclaimer' => 'Use only metrics and claims you can verify. Add the client name, testimonial, or logo when permission is available.',
            'disclaimerClass' => 'small mt-3 mb-0',
        ],

        'process' => [
            'enabled' => true,
            'id' => 'how-it-works',
            'tag' => 'section',
            'class' => 'section-space bg-soft',
            'containerClass' => 'container',
            'introClass' => 'section-intro',
            'eyebrow' => 'How It Works',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'Turn uncertainty into a focused sequence of decisions and improvements.',
            'headingTag' => 'h2',
            'description' => 'The process creates enough clarity to act without delaying progress while searching for a perfect plan.',
            'descriptionClass' => 'mt-3',
            'rowClass' => 'row g-4',
            'columnClass' => 'col-md-6 col-xl-3',
            'cardClass' => 'process-card process-card-strategy h-100',
            'stepClass' => 'process-step',
            'titleClass' => 'h5',
            'bodyClass' => 'mb-0',
            'items' => [
                [
                    'title' => 'Diagnose',
                    'description' => 'Review goals, systems, workflows, performance data, customer experience, and the issues creating the most friction.',
                ],
                [
                    'title' => 'Prioritize',
                    'description' => 'Rank opportunities by expected impact, effort, urgency, risk, and dependency so the next move is clear.',
                ],
                [
                    'title' => 'Plan & Execute',
                    'description' => 'Create a practical roadmap and improve the highest-value systems, experiences, workflows, or measurement gaps.',
                ],
                [
                    'title' => 'Measure & Refine',
                    'description' => 'Evaluate real results, capture what was learned, and update priorities as the business and market change.',
                ],
            ],
        ],

        'founder' => [
            'enabled' => true,
            'id' => 'founder',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'panelClass' => 'founder-panel',
            'rowClass' => 'row align-items-center g-4',
            'avatarColumnClass' => 'col-lg-auto',
            'contentColumnClass' => 'col-lg',
            'buttonColumnClass' => 'col-lg-auto',
            'avatar' => [
                'type' => 'initials',
                'value' => 'JB',
                'imageUrl' => null,
                'alt' => 'Joe Brown',
                'class' => 'founder-avatar founder-avatar-amber',
            ],
            'quoteMark' => '“',
            'quoteMarkClass' => 'quote-mark',
            'heading' => 'Good strategy should make the next decision easier not make the business more dependent on a consultant.',
            'headingTag' => 'h2',
            'headingClass' => 'h3',
            'description' => 'Skale is led by Joe Brown, a technology and growth partner with more than 20 years of experience helping businesses modernize systems, improve operations, and turn complex challenges into practical solutions.',
            'descriptionClass' => 'mb-2',
            'emphasis' => 'You receive senior-level thinking, direct communication, and recommendations based on what your business actually needs.',
            'emphasisClass' => 'mb-0',
            'emphasisTextClass' => 'text-dark',
            'cta' => [
                'label' => 'Learn About Skale',
                'url' => '/about',
                'class' => 'btn btn-outline-dark',
            ],
        ],

        'qualification' => [
            'enabled' => true,
            'id' => 'qualification',
            'tag' => 'section',
            'class' => 'section-space pt-0',
            'containerClass' => 'container',
            'rowClass' => 'row g-5 align-items-center',
            'contentColumnClass' => 'col-lg-6',
            'itemsColumnClass' => 'col-lg-6',
            'itemsRowClass' => 'row g-3',
            'itemColumnClass' => 'col-12',
            'itemClass' => 'd-flex gap-3 p-3 border rounded-4 h-100 qualification-item-strategy',
            'eyebrow' => 'Who This Is For',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'A strong fit for businesses that need clarity before committing more time, money, or technology.',
            'headingTag' => 'h2',
            'iconClass' => 'bi bi-check-circle-fill text-amber fs-5',
            'titleClass' => 'd-block',
            'descriptionClass' => 'text-secondary',
            'items' => [
                [
                    'title' => 'You are generating activity, but not enough qualified opportunities.',
                    'description' => 'Traffic, campaigns, and referrals are not consistently becoming customers.',
                ],
                [
                    'title' => 'Your team relies on too many manual steps and disconnected tools.',
                    'description' => 'Growth is creating more work instead of greater efficiency.',
                ],
                [
                    'title' => 'You want a long-term partner who can connect strategy and execution.',
                    'description' => 'You need more than a vendor completing isolated tasks.',
                ],
            ],
        ],

        'faq' => [
            'enabled' => true,
            'id' => 'faq',
            'tag' => 'section',
            'class' => 'section-space bg-soft',
            'containerClass' => 'container',
            'rowClass' => 'row g-5',
            'introColumnClass' => 'col-lg-5',
            'accordionColumnClass' => 'col-lg-7',
            'eyebrow' => 'Common Questions',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'What businesses usually want to know before starting a strategy or optimization engagement.',
            'headingTag' => 'h2',
            'description' => 'You do not need to arrive with a fully defined project. The purpose of the first conversation is to clarify the problem, desired outcome, and most useful next step.',
            'descriptionClass' => 'mt-3',
            'accordionId' => 'strategyOptimizationFaq',
            'accordionClass' => 'accordion accordion-strategy',
            'itemClass' => 'accordion-item',
            'headerClass' => 'accordion-header',
            'buttonClass' => 'accordion-button',
            'collapsedButtonClass' => 'accordion-button collapsed',
            'collapseClass' => 'accordion-collapse collapse',
            'openCollapseClass' => 'accordion-collapse collapse show',
            'bodyClass' => 'accordion-body',
            'allowMultipleOpen' => false,
            'items' => [
                [
                    'id' => 'faq-strategy-and-optimization',
                    'question' => 'What does a strategy engagement produce?',
                    'answer' => 'Deliverables may include an assessment, system map, prioritized findings, performance baseline, recommended architecture, implementation roadmap, KPI framework, or experiment plan. The goal is to create enough clarity to take responsible action.',
                    'open' => true,
                ],
                [
                    'id' => 'faq-current-tools',
                    'question' => 'Can Skale implement the recommendations?',
                    'answer' => 'Yes. Skale can remain involved through design, development, integration, automation, analytics, marketing, training, and ongoing optimization. Strategy and execution can also be separated when your internal team or another partner will handle implementation.',
                    'open' => false,
                ],
                [
                    'id' => 'faq-one-priority',
                    'question' => 'Can we begin with one decision or performance problem?',
                    'answer' => 'Yes. A focused engagement can be the best starting point when there is one urgent decision, underperforming funnel, technology concern, reporting gap, or operational bottleneck.',
                    'open' => false,
                ],
                [
                    'id' => 'faq-success',
                    'question' => 'How is optimization success measured?',
                    'answer' => 'Success measures are defined before changes are made. Depending on the engagement, they may include conversion rate, lead quality, acquisition cost, response time, manual effort, data accuracy, operating cost, delivery speed, system reliability, or revenue contribution.',
                    'open' => false,
                ],
                [
                    'id' => 'faq-consultation',
                    'question' => 'What happens during the free growth audit call?',
                    'answer' => 'We discuss your goals, current priorities, systems, performance concerns, and where decisions feel unclear. The call is used to identify the most important constraint and determine the most useful next step.',
                    'open' => false,
                ],
            ],
        ],

        'finalCta' => [
            'enabled' => true,
            'id' => 'final-cta',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'panelClass' => 'final-cta final-cta-strategy text-center',
            'rowClass' => 'row justify-content-center',
            'columnClass' => 'col-lg-9',
            'badge' => 'Start with clarity',
            'badgeClass' => 'badge rounded-pill bg-amber-subtle text-amber-emphasis mb-3',
            'heading' => 'Find out what your business should improve next and what can wait.',
            'headingTag' => 'h2',
            'description' => 'Schedule a free growth audit to discuss your current priorities, systems, performance gaps, and the most valuable place to focus first.',
            'descriptionClass' => 'lead mt-3 mb-4',
            'buttons' => [
                'wrapperClass' => 'd-flex flex-column flex-sm-row justify-content-center gap-3',
                'items' => [
                    [
                        'label' => 'Book My Free Growth Audit',
                        'url' => $_ENV['SITE_URL'].$_ENV['URL_CONTACT'],
                        'class' => 'btn btn-amber btn-lg',
                        'iconClass' => null,
                    ],
                    [
                        'label' => '732-925-4044',
                        'url' => 'tel:+17329254044',
                        'class' => 'btn btn-outline-light btn-lg',
                        'iconClass' => 'bi bi-telephone me-2',
                    ],
                ],
            ],
            'note' => 'No obligation. No generic strategy package. A practical conversation focused on the decisions your business needs to make.',
            'noteClass' => 'small mt-3 mb-0',
        ],
    ],
];
