<?php

declare(strict_types=1);

return array (
  'text_contact_skale' => 'Contact skale.',
  'text_build_faster' => 'Build Faster.',
  'text_scale_smarter' => 'Scale Smarter.',
  'text_websites_software_automation_and_marketing_systems' => 'Websites, software, automation, and marketing systems designed to help your business grow efficiently and generate measurable results.',
  'text_custom_built_solutions' => '&check; Custom-built solutions',
  'text_fast_response_times' => '&check; Fast response times',
  'text_strategy_execution' => '&check; Strategy + execution',
  'text_long_term_support' => '&check; Long-term support',
  'text_start_your_project' => 'Start Your Project',
  'text_tell_us_about_your_goals_and' => 'Tell us about your goals and we\'ll reach out within 1 business day.',
  'text_no_pressure_no_obligation_just_a' => 'No pressure. No obligation. Just a conversation about your goals.',
  'text_why_businesses_choose_skale' => 'Why Businesses Choose skale.',
  'text_built_differently' => 'Built Differently.',
  'text_built_to_scale' => 'Built to Scale.',
  'text_strategy_first' => 'Strategy First',
  'text_we_build_systems_designed_around_growth' => 'We build systems designed around growth, not templates.',
  'text_built_to_scale_2' => 'Built to Scale',
  'text_every_solution_is_designed_for_long' => 'Every solution is designed for long-term performance and flexibility.',
  'text_fast_execution' => 'Fast Execution',
  'text_move_quickly_without_sacrificing_quality_or' => 'Move quickly without sacrificing quality or strategic thinking.',
  'text_real_partnership' => 'Real Partnership',
  'text_we_stay_involved_beyond_launch_to' => 'We stay involved beyond launch to optimize and support growth.',
  'text_100' => '100+',
  'text_projects_delivered' => 'Projects Delivered',
  'text_1_day' => '1 Day',
  'text_average_response_time' => 'Average Response Time',
  'text_custom' => 'Custom',
  'text_tailored_solutions' => 'Tailored Solutions',
  'text_ongoing' => 'Ongoing',
  'text_long_term_support_2' => 'Long-Term Support',
  'text_what_happens_next' => 'What Happens Next?',
  'text_simple_process' => 'Simple Process.',
  'text_clear_direction' => 'Clear Direction.',
  'text_1' => '1',
  'text_discovery_call' => 'Discovery Call',
  'text_we_learn_about_your_business_systems' => 'We learn about your business, systems, goals, and challenges.',
  'text_2' => '2',
  'text_strategy_recommendations' => 'Strategy & Recommendations',
  'text_we_identify_opportunities_and_propose_the' => 'We identify opportunities and propose the best path forward.',
  'text_3' => '3',
  'text_build_scale' => 'Build & Scale',
  'text_we_execute_solutions_designed_to_grow' => 'We execute solutions designed to grow with your business long-term.',
  'text_ready_to_build_something_better' => 'Ready to Build Something Better?',
  'text_let_s_create_systems_that_help' => 'Let\'s create systems that help your business scale faster, operate smarter, and generate measurable growth.',
  'text_book_a_free_consultation' => 'Book a Free Consultation',
  'text_view_solutions' => 'View Solutions',
  'aria_label_contact_page_schedule_consultation_button' => 'contact page schedule consultation button',
  'aria_label_contact_page_view_solutions_button' => 'contact page view solutions button',
);
