<?php

declare(strict_types=1);

return array (
  'text_websites_automation_software_systems' => 'Websites &bull; Automation &bull; Software &bull; Systems',
  'text_fix_the_technology_problems_slowing_down_your' => 'Fix the technology problems.',
  'text_fix_the_technology_problems_slowing_down_your_gradient' => 'slowing down your business.',
  'text_skale_helps_growing_businesses_fix_websites_that' => 'Skale helps growing businesses fix websites that don\'t convert, automate repetitive work, connect disconnected systems, build better software, and understand what\'s actually driving growth.',
  'text_disconnected_systems' => 'Disconnected systems',
  'text_manual_processes' => 'Manual processes',
  'text_websites_that_dont_convert' => 'Websites that don\'t convert',
  'text_tell_me_whats_not_working' => 'Tell Me What\'s Not Working',
  'text_see_problems_we_solve' => 'See Problems We Solve',
  'text_20_years' => '20+ years',
  'text_engineering_technology_experience' => 'Engineering & technology experience',
  'text_founder_led' => 'Founder-led',
  'text_work_directly_with_senior_expertise' => 'Work directly with senior expertise',
  'text_business_first' => 'Business-first',
  'text_solve_the_problem_before_choosing_the_tool' => 'Solve the problem before choosing the tool',
  'text_start_with_the_problem' => 'Start With The Problem',
  'text_you_dont_need_to_know_which_service' => 'You don\'t need to know which service you need. You just need to know what isn\'t working.',
  'text_most_businesses_dont_have_a_technology_problem' => 'Most businesses don\'t have a “technology problem.” They have lost leads, wasted time, disconnected information, unreliable processes, or systems that can\'t keep up.',
  'problems' => array(
    array(
      'heading' => '01 / CONVERSION',
      'title' => 'You\'re getting traffic, but not enough leads.',
      'text' => 'Visitors reach your website but leave without contacting you, requesting a quote, or understanding why they should choose your business.',
      'link_text' => 'Fix website conversion →',
      'link' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/websites-and-conversion',
    ),
    array(
      'heading' => '02 / EFFICIENCY',
      'title' => 'Your team is doing work that should happen automatically.',
      'text' => 'Employees copy data, update spreadsheets, send routine emails, prepare reports, and repeat the same processes every day.',
      'link_text' => 'Reduce manual work →',
      'link' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/automation-crm-and-integrations',
    ),
    array(
      'heading' => '03 / SYSTEMS',
      'title' => 'Your systems don\'t talk to each other.',
      'text' => 'Leads, customer information, reporting, email, spreadsheets, and software live in different places and require constant manual handoffs.',
      'link_text' => 'Connect your systems →',
      'link' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/software-and-business-systems',
    ),
    array(
      'heading' => '04 / SCALE',
      'title' => 'The systems that used to work are becoming bottlenecks.',
      'text' => 'More customers, employees, data, and activity are exposing limitations in the way your business operates.',
      'link_text' => 'Find the bottleneck →',
      'link' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/marketing-analytics-and-growth',
    ),
  ),
  'text_tell_me_whats_not_working_2' => 'Tell Me What\'s Not Working',
  'text_selected_work_results' => 'Selected Work & Results',
  'text_experience_solving_the_kinds_of_problems_skale' => 'Experience solving the kinds of problems Skale is built to solve.',
  'text_skale_is_a_newer_company_but_the' => 'Skale is a newer company, but the experience behind it spans more than two decades of software engineering, platform modernization, automation, data systems, websites, and technology leadership.',
  'text_weeks_hours' => 'Weeks → Hours',
  'text_automated_a_complex_customer_onboarding_workflow' => 'Automated a complex customer onboarding workflow',
  'text_replaced_a_multi_team_manually_coordinated_data' => 'Replaced a multi-team, manually coordinated data onboarding process with an automated cloud workflow that detected incoming files, processed information, and moved it into the systems that needed it.',
  'text_automation_integration_data' => 'Automation &bull; Integration &bull; Data',
  'text_70k_1m' => '70K → 1M+',
  'text_helped_scale_a_large_product_data_platform' => 'Helped scale a large product data platform',
  'text_modernized_the_systems_behind_a_growing_data' => 'Modernized the systems behind a growing data platform as its catalog expanded from roughly 70,000 records to more than one million, while improving how data was managed and delivered.',
  'text_software_architecture_scale' => 'Software &bull; Architecture &bull; Scale',
  'text_40_faster' => '~40% Faster',
  'text_improved_application_performance_and_efficiency' => 'Improved application performance and efficiency',
  'text_identified_application_and_workflow_bottlenecks_improved_platform' => 'Identified application and workflow bottlenecks, improved platform performance by approximately 40%, and used automation to reduce manual processing across recurring operations.',
  'text_performance_software_optimization' => 'Performance &bull; Software &bull; Optimization',
  'text_selected_results_reflect_work_completed_by_skale' => 'Selected results reflect work completed by Skale founder Joe Brown during professional and consulting engagements prior to founding Skale. Client and employer details are omitted where appropriate.',
  // 'testimonials' => array(
  //   array(
  //     'text' => 'Skale took the time to understand how our business actually works, then delivered a practical solution that made our process faster, clearer, and easier to manage.',
  //     'author' => 'Alex Morgan',
  //     'role' => 'Operations Director',
  //     'company' => 'Northstar Solutions',
  //   ),
  // ),
  'text_how_skale_can_help' => 'How Skale Can Help',
  'text_practical_help_across_the_technology_behind_your' => 'Practical help across the technology behind your business.',
  'text_start_with_one_problem_or_connect_several' => 'Start with one problem or connect several areas together. You don\'t have to figure out which category your problem belongs in before reaching out.',
  'services' => array(
    array(
      'number' => '01',
      'title' => 'Websites & Conversion',
      'text' => 'Make your website easier to understand, easier to trust, and more effective at turning visitors into real opportunities.',
      'children' => array(
        array('title' => 'Website Design & Development', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/website-design-and-development'),
        array('title' => 'WordPress Development', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/wordpress-development'),
        array('title' => 'Website Rescue', 'url' => $_ENV['WEB_ROOT'].'website-rescue'),
        // array('title' => 'Landing Pages', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/landing-pages'),
        array('title' => 'Conversion Optimization', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/conversion-optimization'),
      ),
    ),

    array(
      'number' => '02',
      'title' => 'Automation, CRM & Integrations',
      'text' => 'Reduce repetitive work and make information move automatically between the people and platforms that depend on it.',
      'children' => array(
        array('title' => 'Workflow Automation', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/workflow-automation'),
        array('title' => 'System Integrations', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/system-integrations'),
        array('title' => 'CRM Solutions', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/crm-solutions'),
        array('title' => 'Marketing Automation', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/marketing-automation'),
        // array('title' => 'Data Synchronization', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/data-synchronization'),
      ),
    ),

    array(
      'number' => '03',
      'title' => 'Software & Business Systems',
      'text' => 'Build or modernize the software your business needs when spreadsheets and off-the-shelf tools no longer fit the way you work.',
      'children' => array(
        array('title' => 'Custom Software Development', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/custom-software-development'),
        array('title' => 'Internal Business Tools', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/internal-business-tools'),
        // array('title' => 'Customer & Partner Portals', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/customer-and-partner-portals'),
        // array('title' => 'Software Modernization', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/software-modernization'),
        // array('title' => 'IT & Technology Solutions', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/it-and-technology-solutions'),
      ),
    ),

    array(
      'number' => '04',
      'title' => 'Marketing, Analytics & Growth',
      'text' => 'Understand where opportunities come from, improve the customer journey, and make smarter decisions with better marketing and reporting.',
      'children' => array(
        // array('title' => 'Online Marketing', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/online-marketing'),
        array('title' => 'SEO', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/search-engine-optimization'),
        array('title' => 'PPC / Paid Advertising', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/ppc-paid-advertising'),
        array('title' => 'Email Marketing', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/email-marketing'),
        // array('title' => 'Marketing Analytics', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/marketing-analytics'),
        array('title' => 'Analytics & Reporting', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/analytics-and-reporting'),
        // array('title' => 'Strategy & Optimization', 'url' => $_ENV['URL_SERVICES_SOLUTIONS'].'/strategy-and-optimization'),
      ),
    ),
  ),

  'text_not_sure_where_your_problem_belongs' => 'Not sure where your problem belongs?',
  'text_thats_normal_a_lead_generation_problem_might' => 'That\'s normal. A lead-generation problem might involve your website, analytics, CRM, messaging, or follow-up. Skale looks at the complete system instead of forcing the problem into a predefined service.',
  'text_tell_me_whats_not_working_3' => 'Tell Me What\'s Not Working',
  'text_the_skale_approach' => 'The Skale Approach',
  'text_fix_the_whole_journey_not_just_one' => 'Fix the whole journey, not just one disconnected piece.',
  'text_a_website_can_generate_traffic_and_still' => 'A website can generate traffic and still fail if leads disappear into an inbox. Marketing can create opportunities and still fail if nobody follows up. Better systems connect every step.',
  'text_marketing' => 'Marketing',
  'text_website' => 'Website',
  'text_crm' => 'CRM',
  'text_automation' => 'Automation',
  'text_reporting' => 'Reporting',
  'text_growth' => 'Growth',
  'text_technical_depth' => 'Technical Depth',
  'text_experienced_across_the_systems_behind_modern_businesses' => 'Experienced across the systems behind modern businesses.',
  'text_technology_is_selected_based_on_the_problem' => 'Technology is selected based on the problem, not because Skale needs to sell you a particular platform.',
  'text_wordpress' => 'WordPress',
  'text_react' => 'React',
  'text_node_js' => 'Node.js',
  'text_php' => 'PHP',
  'text_rest_apis' => 'REST APIs',
  'text_mysql' => 'MySQL',
  'text_google_cloud' => 'Google Cloud',
  'text_aws' => 'AWS',
  'text_azure' => 'Azure',
  'text_crm_integrations' => 'CRM Integrations',
  'text_marketing_platforms' => 'Marketing Platforms',
  'text_analytics' => 'Analytics',
  'text_who_skale_is_for' => 'Who Skale Is For',
  'text_a_strong_fit_when_growing_starts_creating' => 'A strong fit when growing starts creating friction.',
  'text_skale_works_best_with_businesses_that_have' => 'Skale works best with businesses that have outgrown simple fixes but don\'t need the cost and layers of a large agency or consulting firm.',
  'text_tell_me_whats_not_working_4' => 'Tell Me What\'s Not Working',
  'text_growing_small_and_midsize_businesses' => 'Growing small and midsize businesses',
  'text_your_company_has_real_customers_and_momentum' => 'Your company has real customers and momentum, but the technology behind the business hasn\'t kept pace.',
  'text_teams_relying_on_manual_processes' => 'Teams relying on manual processes',
  'text_spreadsheets_emails_duplicate_entry_and_repetitive_administrative' => 'Spreadsheets, emails, duplicate entry, and repetitive administrative work are consuming too much time.',
  'text_businesses_with_disconnected_tools' => 'Businesses with disconnected tools',
  'text_your_website_crm_marketing_operations_and_reporting' => 'Your website, CRM, marketing, operations, and reporting platforms don\'t reliably share the information they should.',
  'text_businesses_facing_an_unclear_technology_problem' => 'Businesses facing an unclear technology problem',
  'text_you_know_something_is_inefficient_or_limiting' => 'You know something is inefficient or limiting growth, but you don\'t yet know whether the answer is software, automation, marketing, or a better process.',
  'text_how_it_works' => 'How It Works',
  'text_start_with_the_business_problem_technology_comes' => 'Start with the business problem. Technology comes second.',
  'text_1' => '1',
  'text_find_the_friction' => 'Find the friction',
  'text_understand_whats_happening_today_where_time_or' => 'Understand what\'s happening today, where time or opportunities are being lost, and what is causing the problem.',
  'text_2' => '2',
  'text_identify_the_highest_impact_fix' => 'Identify the highest-impact fix',
  'text_determine_what_will_create_the_most_meaningful' => 'Determine what will create the most meaningful improvement before adding software, redesigning anything, or changing platforms.',
  'text_3' => '3',
  'text_build_connect_and_improve' => 'Build, connect, and improve',
  'text_implement_the_solution_measure_whether_its_working' => 'Implement the solution, measure whether it\'s working, and improve the system as your business changes.',
  'text_founder_led_2' => 'Founder-Led',
  'text_skale_is_new_the_experience_behind_it' => 'Skale is new. The experience behind it isn\'t.',
  'text_im_joe_brown_founder_of_skale_ive' => 'I\'m Joe Brown, founder of Skale. I\'ve spent more than 20 years building websites, software, data platforms, integrations, automation, and business technology.',
  'text_i_created_skale_to_bring_that_experience' => 'I created Skale to bring that experience directly to growing businesses without forcing them to coordinate separate website developers, software teams, marketing vendors, automation consultants, and technical advisors.',
  'text_youll_work_directly_with_someone_who_can' => 'You\'ll work directly with someone who can understand the business problem, evaluate the technology behind it, and help determine what actually needs to change.',
  'text_learn_more_about_joe_and_skale' => 'Learn more about Joe and Skale →',
  'text_senior_level_experience' => 'Senior-level experience',
  'text_applied_directly_to_your_project' => 'Applied directly to your project.',
  'text_direct_communication' => 'Direct communication',
  'text_no_layers_of_account_managers_between_you' => 'No layers of account managers between you and the work.',
  'text_no_predetermined_solution' => 'No predetermined solution',
  'text_fix_whats_actually_causing_the_problem' => 'Fix what\'s actually causing the problem.',
  'text_practical_insights' => 'Practical Insights',
  'text_see_how_skale_approaches_common_business_problems' => 'See how Skale approaches common business problems.',
  'text_not_ready_to_contact_anyone_yet_start' => 'Not ready to contact anyone yet? Start here.',
  // 'text_websites_conversion_2' => 'Websites & Conversion',
  // 'text_why_your_website_gets_traffic_but_no' => 'Why Your Website Gets Traffic But No Leads',
  // 'text_see_the_problems_that_can_stop_website' => 'See the problems that can stop website traffic from turning into actual inquiries.',
  // 'text_read_the_article' => 'Read the article →',
  // 'text_systems_integration' => 'Systems & Integration',
  // 'text_the_hidden_cost_of_disconnected_business_systems' => 'The Hidden Cost of Disconnected Business Systems',
  // 'text_see_how_disconnected_crms_email_platforms_websites' => 'See how disconnected CRMs, email platforms, websites, spreadsheets, and reporting create hidden work.',
  // 'text_read_the_article_2' => 'Read the article →',
  // 'text_automation_2' => 'Automation',
  // 'text_stop_paying_employees_to_do_robot_work' => 'Stop Paying Employees to Do Robot Work',
  // 'text_identify_repetitive_work_that_may_be_costing' => 'Identify repetitive work that may be costing your business more than you realize.',
  // 'text_read_the_article_3' => 'Read the article →',
  'text_a_better_first_step' => 'A Better First Step',
  'text_tell_me_whats_not_working_5' => 'Tell me what\'s not working.',
  'text_you_dont_need_a_project_plan_technical' => 'You don\'t need a project plan, technical specification, or even a clear idea of what service you need.',
  'text_send_a_short_description_of_the_problem' => 'Send a short description of the problem and I\'ll review what you\'ve shared and recommend a practical next step.',
  'text_text' => '✓',
  'text_no_obligation_to_schedule_a_call' => 'No obligation to schedule a call',
  'text_text_2' => '✓',
  'text_no_generic_sales_pitch' => 'No generic sales pitch',
  'text_text_3' => '✓',
  'text_you_dont_need_to_diagnose_the_solution' => 'You don\'t need to diagnose the solution',
  'text_text_4' => '✓',
  'text_direct_response_from_skales_founder' => 'Direct response from Skale\'s founder',
  'text_free_quick_assessment' => 'Free Quick Assessment',
  'text_whats_getting_in_your_way' => 'What\'s getting in your way?',
  'text_a_few_sentences_are_enough' => 'A few sentences are enough.',
  'text_name' => 'Name',
  'text_email' => 'Email',
  'text_website_2' => 'Website',
  'text_optional' => '(optional)',
  'text_whats_not_working' => 'What\'s not working?',
  'text_tell_me_whats_not_working_6' => 'Tell Me What\'s Not Working',
  'text_no_spam_no_aggressive_sales_follow_up' => 'No spam. No aggressive sales follow-up. I\'ll review what you send and tell you what I think the best next step is, even if that isn\'t a Skale project.',
  'text_https' => 'https://',
  'text_example_were_getting_website_traffic_but_almost' => 'Example: We\'re getting website traffic but almost nobody fills out our contact form...',
);
