<?php

declare(strict_types=1);

return [
    // 'name' => 'Automation & Software',
    // 'slug' => 'automation-and-software',

    // 'seo' => [
    //     'title' => 'Business Automation & Custom Software Development | Skale',
    //     'description' => 'Reduce manual work, connect disconnected systems, and build custom software that helps your business operate faster, more accurately, and at greater scale.',
    //     'canonical' => '/solutions/automation-and-software',
    //     'robots' => 'index,follow',
    // ],

    'sections' => [
        'hero' => [
            'enabled' => true,
            'id' => 'automation-software-hero',
            'tag' => 'section',
            'class' => 'hero hero-automation-software position-relative overflow-hidden text-white',
            'containerClass' => 'container position-relative',
            'rowClass' => 'row align-items-center g-5',
            'contentColumnClass' => 'col-lg-7',
            'formColumnClass' => 'col-lg-5',
            'contentClass' => 'hero-copy pe-lg-4',
            'eyebrow' => 'Automation & Software',
            'eyebrowClass' => 'eyebrow eyebrow-light',
            'heading' => 'Replace repetitive work and disconnected systems with technology that',
            'highlight' => 'moves your business forward.',
            'headingTag' => 'h1',
            'headingClass' => 'display-4 fw-bold',
            'highlightClass' => 'text-highlight text-cyan',
            'description' => 'Skale designs workflow automation, system integrations, internal tools, and custom software that reduce manual effort, improve accuracy, and give your team more time to focus on customers and growth.',
            'descriptionClass' => 'hero-lead lead mt-4 mb-0 text-white-75',
            'background' => [
                'class' => 'hero-automation-software-bg',
                'overlayClass' => 'hero-automation-software-overlay',
                'decorations' => [
                    ['class' => 'hero-circuit-grid', 'ariaHidden' => true],
                    ['class' => 'hero-glow hero-glow-one', 'ariaHidden' => true],
                    ['class' => 'hero-glow hero-glow-two', 'ariaHidden' => true],
                ],
            ],
            'benefits' => [
                'class' => 'hero-checks hero-checks-light',
                'ariaLabel' => 'Automation and software benefits',
                'iconClass' => 'bi bi-check-circle-fill text-cyan',
                'items' => [
                    'Built around your real workflows',
                    'Connects the tools you already use',
                    'Designed for reliability, adoption, and scale',
                ],
            ],
            'buttons' => [
                'wrapperClass' => 'd-flex flex-column flex-sm-row gap-3',
                'items' => [
                    [
                        'label' => 'Get Your Free Workflow Review',
                        'url' => '#consultation',
                        'class' => 'btn btn-primary btn-lg',
                    ],
                    [
                        'label' => 'See How It Works',
                        'url' => '#how-it-works',
                        'class' => 'btn btn-outline-dark btn-lg',
                    ],
                ],
            ],
            'note' => [
                'text' => 'No generic software pitch. We start by identifying the work that wastes the most time, creates the most errors, or prevents your business from scaling.',
                'class' => 'hero-note hero-note-light',
                'iconClass' => 'bi bi-shield-check',
            ],
            'form' => [
                'enabled' => true,
                'anchorId' => 'consultation',
                'wrapperClass' => 'hero-form-wrap',
                'cardClass' => 'lead-form-card lead-form-card-automation',
                'headerClass' => 'mb-4',
                'badge' => 'Free 30-minute workflow review',
                'badgeClass' => 'badge text-bg-light border mb-3',
                'heading' => 'Find the work your business should stop doing manually',
                'headingTag' => 'h2',
                'headingClass' => 'h3 mb-2',
                'description' => 'Tell us where your team loses time or where your systems break down. We will help identify the most practical opportunity to automate, connect, or simplify.',
                'descriptionClass' => 'mb-0 text-secondary',
                'action' => '/post-lead-form',
                'method' => 'POST',
                'id' => 'automation-software-lead-form',
                'class' => 'ajaxForm',
                'attributes' => [
                    'dataMetaFormName' => 'automation-and-software-form',
                    'dataMetaSuccessEvent' => 'Lead',
                ],
                'fieldGroups' => ['business-details' => 'row g-3 mb-3'],
                'fields' => [
                    ['type' => 'text', 'name' => 'name', 'id' => 'name', 'label' => 'Name', 'required' => true, 'autocomplete' => 'name', 'wrapperClass' => 'mb-3', 'labelClass' => 'form-label fw-semibold', 'inputClass' => 'form-control'],
                    ['type' => 'email', 'name' => 'email', 'id' => 'email', 'label' => 'Email', 'required' => true, 'autocomplete' => 'email', 'wrapperClass' => 'mb-3', 'labelClass' => 'form-label fw-semibold', 'inputClass' => 'form-control'],
                    ['type' => 'tel', 'name' => 'phone', 'id' => 'phone', 'label' => 'Phone', 'labelSuffix' => '(optional)', 'required' => false, 'autocomplete' => 'tel', 'wrapperClass' => 'col-sm-6', 'labelClass' => 'form-label fw-semibold', 'labelSuffixClass' => 'fw-normal text-secondary', 'inputClass' => 'form-control', 'group' => 'business-details'],
                    ['type' => 'select', 'name' => 'team_size', 'id' => 'team-size', 'label' => 'Team size', 'wrapperClass' => 'col-sm-6', 'labelClass' => 'form-label fw-semibold', 'inputClass' => 'form-select', 'group' => 'business-details', 'options' => [
                        ['label' => 'Select', 'value' => ''], ['label' => 'Just me', 'value' => '1'], ['label' => '2-5 people', 'value' => '2-5'], ['label' => '6-15 people', 'value' => '6-15'], ['label' => '16-50 people', 'value' => '16-50'], ['label' => '50+ people', 'value' => '50-plus'],
                    ]],
                    ['type' => 'select', 'name' => 'primary_need', 'id' => 'primary-need', 'label' => 'What do you need most?', 'wrapperClass' => 'mb-3', 'labelClass' => 'form-label fw-semibold', 'inputClass' => 'form-select', 'options' => [
                        ['label' => 'Select', 'value' => ''], ['label' => 'Automate repetitive work', 'value' => 'workflow-automation'], ['label' => 'Connect existing systems', 'value' => 'system-integrations'], ['label' => 'Build a custom internal tool', 'value' => 'internal-tool'], ['label' => 'Develop a customer-facing platform', 'value' => 'customer-platform'], ['label' => 'Modernize existing software', 'value' => 'software-modernization'], ['label' => 'Not sure yet', 'value' => 'not-sure'],
                    ]],
                    ['type' => 'textarea', 'name' => 'comment', 'id' => 'comment', 'label' => 'What process or system is creating friction?', 'placeholder' => 'Describe the manual work, disconnected tools, reporting problem, or software limitation...', 'rows' => 4, 'wrapperClass' => 'mb-4', 'labelClass' => 'form-label fw-semibold', 'inputClass' => 'form-control'],
                    ['type' => 'hidden', 'name' => 'interests[]', 'value' => 'automation-and-software'],
                ],
                'submit' => ['label' => 'Request My Free Workflow Review', 'class' => 'btn btn-skale btn-lg w-100'],
                'privacy' => ['text' => 'No sales pressure. Your information stays private.', 'class' => 'small text-secondary text-center mt-3 mb-0', 'iconClass' => 'fa-solid fa-lock me-1'],
            ],
        ],

        'trustStrip' => [
            'enabled' => true,
            'id' => 'trust-strip',
            'tag' => 'section',
            'class' => 'trust-strip trust-strip-automation',
            'containerClass' => 'container',
            'rowClass' => 'row row-cols-2 row-cols-lg-4 g-3',
            'columnClass' => 'col',
            'itemClass' => 'trust-item',
            'ariaLabel' => 'Why businesses trust Skale for automation and software',
            'items' => [
                ['iconClass' => 'bi bi-person-check', 'title' => 'Senior Engineering', 'description' => 'Direct access to experienced technical leadership'],
                ['iconClass' => 'bi bi-diagram-3', 'title' => 'Workflow First', 'description' => 'Technology designed around how your business operates'],
                ['iconClass' => 'bi bi-plug', 'title' => 'Connected Systems', 'description' => 'Tools, data, and processes working together'],
                ['iconClass' => 'bi bi-headset', 'title' => 'Long-Term Support', 'description' => 'Ongoing improvement after launch'],
            ],
        ],

        'problems' => [
            'enabled' => true,
            'id' => 'problems',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'introClass' => 'section-intro',
            'eyebrow' => 'The Cost of Manual Work',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'Operational friction quietly drains time, money, and momentum.',
            'headingTag' => 'h2',
            'description' => 'When employees rely on repetitive steps, disconnected applications, and software that no longer fits the business, growth creates more work instead of more capacity.',
            'descriptionClass' => 'mt-3',
            'rowClass' => 'row g-4',
            'columnClass' => 'col-md-6 col-xl-3',
            'cardClass' => 'problem-card problem-card-automation h-100',
            'iconWrapperClass' => 'icon-box icon-box-cyan',
            'titleClass' => 'h5',
            'bodyClass' => 'mb-0',
            'items' => [
                ['iconClass' => 'bi bi-arrow-repeat', 'title' => 'Employees repeat the same work', 'description' => 'People copy information, update spreadsheets, send routine messages, and complete predictable tasks by hand.'],
                ['iconClass' => 'bi bi-exclamation-triangle', 'title' => 'Manual steps create errors', 'description' => 'Important details are missed, entered inconsistently, or delayed because the process depends on memory and handoffs.'],
                ['iconClass' => 'bi bi-plug', 'title' => 'Systems do not communicate', 'description' => 'Data is trapped across software, inboxes, spreadsheets, and departments that operate independently.'],
                ['iconClass' => 'bi bi-box-arrow-in-up-right', 'title' => 'Off-the-shelf tools stop fitting', 'description' => 'Your team adapts its process to software limitations instead of using technology designed around the business.'],
            ],
        ],

        'outcomes' => [
            'enabled' => true,
            'id' => 'outcomes',
            'tag' => 'section',
            'class' => 'section-space pt-0',
            'containerClass' => 'container',
            'panelClass' => 'outcome-panel outcome-panel-automation',
            'rowClass' => 'row align-items-center g-5',
            'contentColumnClass' => 'col-lg-5',
            'listColumnClass' => 'col-lg-7',
            'eyebrow' => 'The Outcome',
            'eyebrowClass' => 'eyebrow text-white-50',
            'heading' => 'A more efficient business supported by systems that work the way your team does.',
            'headingTag' => 'h2',
            'description' => 'Skale turns recurring work, disconnected information, and software limitations into dependable workflows your business can measure, improve, and scale.',
            'descriptionClass' => 'mt-3 mb-0 text-white-75',
            'listClass' => 'outcome-list',
            'iconClass' => 'bi bi-check-circle-fill',
            'items' => [
                ['title' => 'Give time back to your team', 'description' => 'Automate repetitive tasks so employees can focus on customers, decisions, and higher-value work.'],
                ['title' => 'Reduce preventable mistakes', 'description' => 'Use consistent rules, validations, notifications, and workflows instead of relying on manual execution.'],
                ['title' => 'Move information automatically', 'description' => 'Connect platforms so data reaches the right system and the right person without duplicate entry.'],
                ['title' => 'Build capacity without adding complexity', 'description' => 'Create software and processes that support more customers, data, and work without unnecessary overhead.'],
            ],
        ],

        'serviceComponents' => [
            'enabled' => true,
            'id' => 'automation-software-services',
            'tag' => 'section',
            'class' => 'section-space bg-soft',
            'containerClass' => 'container',
            'headerRowClass' => 'row align-items-end mb-5 g-3',
            'headingColumnClass' => 'col-lg-8',
            'descriptionColumnClass' => 'col-lg-4',
            'eyebrow' => 'What We Build',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'Practical automation and software built around real business needs.',
            'headingTag' => 'h2',
            'headingClass' => 'mb-0',
            'description' => 'Your engagement can solve one specific bottleneck or create a connected operational system across multiple teams and tools.',
            'descriptionClass' => 'mb-0',
            'rowClass' => 'row g-4',
            'columnClass' => 'col-md-6 col-xl-4',
            'cardClass' => 'service-card service-card-automation h-100',
            'numberClass' => 'service-number',
            'iconWrapperClass' => 'icon-box icon-box-cyan',
            'titleClass' => 'h4',
            'listClass' => 'service-list',
            'listIconClass' => 'bi bi-check2',
            'items' => [
                [
                    'iconClass' => 'bi bi-lightning-charge',
                    'title' => 'Workflow Automation',
                    'description' => 'Turn predictable, repetitive processes into reliable workflows that happen automatically.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/automation',
                    'bullets' => [
                        'Task and approval automation',
                        'Notifications and follow-up sequences',
                        'Scheduled processing and recurring operations',
                    ],
                ],
                [
                    'iconClass' => 'bi bi-link-45deg',
                    'title' => 'System Integrations',
                    'description' => 'Connect the platforms your business depends on so data moves without unnecessary handoffs.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/system-integrations',
                    'bullets' => [
                        'API and third-party integrations',
                        'Data synchronization between platforms',
                        'Webhook and event-driven workflows',
                    ],
                ],
                [
                    'iconClass' => 'bi bi-window-sidebar',
                    'title' => 'Internal Business Tools',
                    'description' => 'Replace scattered spreadsheets and workarounds with focused software designed for your team.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/software-development',
                    'bullets' => [
                        'Operations and administration portals',
                        'Task, project, and workflow systems',
                        'Custom dashboards and management tools',
                    ],
                ],
                [
                    'iconClass' => 'bi bi-code-square',
                    'title' => 'Custom Software Development',
                    'description' => 'Build customer-facing or operational software that supports a unique process or business model.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/software-development',
                    'bullets' => [
                        'Web applications and digital platforms',
                        'Customer and partner portals',
                        'Custom APIs and backend services',
                    ],
                ],
                [
                    'iconClass' => 'bi bi-arrow-clockwise',
                    'title' => 'Software Modernization',
                    'description' => 'Improve aging software that has become slow, unreliable, difficult to maintain, or expensive to operate.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/software-development',
                    'bullets' => [
                        'Legacy system assessment and planning',
                        'Application and database modernization',
                        'Performance, usability, and reliability improvements',
                    ],
                ],
                [
                    'iconClass' => 'bi bi-robot',
                    'title' => 'AI-Assisted Workflows',
                    'description' => 'Apply AI where it creates practical value without adding unnecessary complexity or risk.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/automation-and-software',
                    'bullets' => [
                        'Document and data processing',
                        'Reporting, summarization, and classification',
                        'Human-reviewed AI workflow assistance',
                    ],
                ],
            ],
            'cta' => ['label' => 'Talk Through Your Workflow Gaps', 'url' => '#consultation', 'wrapperClass' => 'text-center mt-5', 'class' => 'btn btn-cyan btn-lg'],
        ],

        'services' => ['enabled' => false, 'id' => 'related-services', 'tag' => 'section', 'class' => 'section-space', 'containerClass' => 'container', 'items' => []],

        'caseStudy' => [
            'enabled' => true,
            'id' => 'case-study',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'panelClass' => 'case-study case-study-automation',
            'rowClass' => 'row align-items-center g-5',
            'contentColumnClass' => 'col-lg-6',
            'metricsColumnClass' => 'col-lg-6',
            'label' => 'Client Transformation',
            'labelClass' => 'case-label',
            'heading' => 'From a week of manual onboarding to an automated process completed in hours.',
            'headingTag' => 'h2',
            'headingClass' => 'mt-2',
            'description' => 'A data business relied on employees across multiple teams to collect files, validate information, transform records, and load customer data into its platform. Skale helped replace that slow, error-prone process with an automated cloud workflow that detected new files, processed the data, and delivered it to the systems that needed it.',
            'descriptionClass' => 'mt-3',
            'lessonLabel' => 'The lesson:',
            'lesson' => 'The best automation does more than accelerate one task. It removes handoffs, improves consistency, and creates operational capacity across the business.',
            'lessonClass' => 'mb-0',
            'metricsRowClass' => 'row g-3',
            'metricColumnClass' => 'col-6',
            'metricClass' => 'metric metric-cyan h-100',
            'metrics' => [
                ['value' => 'Hours', 'label' => 'Instead of weeks to onboard data'],
                ['value' => 'Automated', 'label' => 'File detection and processing'],
                ['value' => 'Fewer', 'label' => 'Manual handoffs and delays'],
                ['value' => 'Scalable', 'label' => 'Cloud-based data workflow'],
            ],
            'disclaimer' => 'Use only approved metrics and client details when publishing. The client name can remain confidential if required.',
            'disclaimerClass' => 'small mt-3 mb-0 text-secondary',
        ],

        'process' => [
            'enabled' => true,
            'id' => 'how-it-works',
            'tag' => 'section',
            'class' => 'section-space bg-soft',
            'containerClass' => 'container',
            'introClass' => 'section-intro',
            'eyebrow' => 'How It Works',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'Solve the workflow before choosing the technology.',
            'headingTag' => 'h2',
            'description' => 'We begin by understanding the business process, then design the simplest dependable system that can deliver the required outcome.',
            'descriptionClass' => 'mt-3',
            'rowClass' => 'row g-4',
            'columnClass' => 'col-md-6 col-xl-3',
            'cardClass' => 'process-card process-card-automation h-100',
            'stepClass' => 'process-step',
            'titleClass' => 'h5',
            'bodyClass' => 'mb-0',
            'items' => [
                ['step' => '1', 'title' => 'Map the Work', 'description' => 'Document the current process, people, systems, data, decisions, delays, and recurring points of failure.'],
                ['step' => '2', 'title' => 'Design the System', 'description' => 'Define the improved workflow, automation rules, integrations, user experience, and measures of success.'],
                ['step' => '3', 'title' => 'Build & Validate', 'description' => 'Develop the solution in focused stages, test it against real scenarios, and refine it with the people who will use it.'],
                ['step' => '4', 'title' => 'Launch & Improve', 'description' => 'Roll out the system, train users, monitor performance, and improve the workflow as the business evolves.'],
            ],
        ],

        'founder' => [
            'enabled' => true,
            'id' => 'founder',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'panelClass' => 'founder-panel',
            'rowClass' => 'row align-items-center g-4',
            'avatarColumnClass' => 'col-lg-auto',
            'contentColumnClass' => 'col-lg',
            'ctaColumnClass' => 'col-lg-auto',
            'avatar' => ['type' => 'initials', 'value' => 'JB', 'image' => null, 'alt' => 'Joe Brown', 'class' => 'founder-avatar founder-avatar-cyan'],
            'quoteMark' => '“',
            'quoteMarkClass' => 'quote-mark',
            'heading' => 'You should not have to translate your business problem into a technical specification before asking for help.',
            'headingTag' => 'h2',
            'headingClass' => 'h3',
            'description' => 'Skale is led by Joe Brown, a technology and growth partner with more than 20 years of experience building software, modernizing platforms, automating workflows, integrating systems, and leading complex technical initiatives.',
            'descriptionClass' => 'mb-2',
            'emphasis' => 'You receive direct senior-level guidance focused on the business result first and the appropriate technology second.',
            'emphasisClass' => 'mb-0 text-dark',
            'cta' => ['label' => 'Learn About Skale', 'url' => '/about', 'class' => 'btn btn-outline-dark'],
        ],

        'qualification' => [
            'enabled' => true,
            'id' => 'qualification',
            'tag' => 'section',
            'class' => 'section-space pt-0',
            'containerClass' => 'container',
            'rowClass' => 'row g-5 align-items-center',
            'headingColumnClass' => 'col-lg-6',
            'itemsColumnClass' => 'col-lg-6',
            'itemsRowClass' => 'row g-3',
            'itemColumnClass' => 'col-12',
            'itemClass' => 'd-flex gap-3 p-3 border rounded-4 h-100 qualification-item-automation',
            'eyebrow' => 'Who This Is For',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'A strong fit for businesses where operational complexity is beginning to limit growth.',
            'headingTag' => 'h2',
            'iconClass' => 'bi bi-check-circle-fill text-cyan fs-5',
            'titleClass' => 'd-block',
            'descriptionClass' => 'text-secondary',
            'items' => [
                ['title' => 'Your team spends too much time on repeatable administrative work.', 'description' => 'Employees are copying data, preparing routine reports, sending updates, or managing predictable processes manually.'],
                ['title' => 'Important information is spread across disconnected systems.', 'description' => 'Your business relies on spreadsheets, email, software platforms, and databases that do not share information reliably.'],
                ['title' => 'Existing software no longer fits the way the business operates.', 'description' => 'Workarounds and platform limitations are slowing employees down or preventing the company from offering something new.'],
                ['title' => 'You want a technical partner who can understand the business behind the request.', 'description' => 'You need strategy, architecture, implementation, training, and ongoing improvement, not simply a developer completing a ticket.'],
            ],
        ],

        'faq' => [
            'enabled' => true,
            'id' => 'faq',
            'tag' => 'section',
            'class' => 'section-space bg-soft',
            'containerClass' => 'container',
            'rowClass' => 'row g-5',
            'introColumnClass' => 'col-lg-5',
            'accordionColumnClass' => 'col-lg-7',
            'eyebrow' => 'Common Questions',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'What businesses usually want to know before automating a process or building custom software.',
            'headingTag' => 'h2',
            'description' => 'You do not need to know exactly what should be built. The first step is understanding the workflow, the business problem, and the result the system needs to produce.',
            'descriptionClass' => 'mt-3',
            'accordionId' => 'automationSoftwareFaq',
            'accordionClass' => 'accordion accordion-automation',
            'itemClass' => 'accordion-item',
            'headerClass' => 'accordion-header',
            'buttonClass' => 'accordion-button',
            'collapsedButtonClass' => 'accordion-button collapsed',
            'collapseClass' => 'accordion-collapse collapse',
            'openCollapseClass' => 'accordion-collapse collapse show',
            'bodyClass' => 'accordion-body',
            'allowMultipleOpen' => false,
            'items' => [
                ['id' => 'faq-automation-opportunities', 'question' => 'How do we know what should be automated?', 'answer' => 'Good automation candidates are usually repeatable, rules-based, time-consuming, error-prone, or dependent on moving information between people and systems. Skale reviews the current process and prioritizes opportunities based on business impact, feasibility, risk, and expected return.', 'open' => true],
                ['id' => 'faq-existing-tools', 'question' => 'Can you automate the software we already use?', 'answer' => 'Often, yes. Many platforms provide APIs, webhooks, exports, integrations, or automation features that can be connected and extended. We first evaluate what your current tools support before recommending new software.', 'open' => false],
                ['id' => 'faq-custom-software', 'question' => 'When does custom software make sense?', 'answer' => 'Custom software can make sense when an important workflow is unique to your business, existing products create too many compromises, manual work has become expensive, or a new digital capability could improve your service or create revenue.', 'open' => false],
                ['id' => 'faq-replace-systems', 'question' => 'Do we need to replace our current systems?', 'answer' => 'Not necessarily. The best solution may be to connect, configure, simplify, or extend what you already use. Replacement is recommended only when the current platform creates significant limitations, cost, risk, or maintenance problems.', 'open' => false],
                ['id' => 'faq-project-start', 'question' => 'Can we start with one workflow or small project?', 'answer' => 'Yes. Starting with a focused, high-impact workflow is often the safest way to prove value, learn how the system should operate, and create a foundation that can expand over time.', 'open' => false],
                ['id' => 'faq-support', 'question' => 'What happens after the automation or software launches?', 'answer' => 'Skale can provide documentation, training, monitoring, maintenance, technical support, and ongoing optimization. The level of support depends on the importance and complexity of the system.', 'open' => false],
                ['id' => 'faq-ai', 'question' => 'Can AI be included in the solution?', 'answer' => 'Yes, when it offers a practical advantage. AI may help classify information, summarize content, process documents, assist users, or identify patterns. We design AI-assisted workflows with appropriate human review, privacy considerations, and fallback behavior.', 'open' => false],
            ],
        ],

        'finalCta' => [
            'enabled' => true,
            'id' => 'final-cta',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'panelClass' => 'final-cta final-cta-automation text-center',
            'rowClass' => 'row justify-content-center',
            'columnClass' => 'col-lg-9',
            'badge' => 'Start with the workflow',
            'badgeClass' => 'badge rounded-pill bg-cyan-subtle text-cyan-emphasis mb-3',
            'heading' => 'Find out which manual process, disconnected system, or software limitation is costing your business the most.',
            'headingTag' => 'h2',
            'description' => 'Schedule a free workflow review to discuss how your team works today and where automation, integration, or custom software could create the greatest practical improvement.',
            'descriptionClass' => 'lead mt-3 mb-4',
            'buttons' => [
                'wrapperClass' => 'd-flex flex-column flex-sm-row justify-content-center gap-3',
                'items' => [
                    [
                        'label' => 'Book My Free Workflow Review',
                        'url' => $_ENV['SITE_URL'] . $_ENV['URL_CONTACT'],
                        'class' => 'btn btn-cyan btn-lg',
                        'iconClass' => null],
                    ['label' => '732-925-4044', 'url' => 'tel:+17329254044', 'class' => 'btn btn-outline-light btn-lg', 'iconClass' => 'bi bi-telephone me-2'],
                ],
            ],
            'note' => 'No obligation. No generic package. A practical conversation focused on how your business actually operates.',
            'noteClass' => 'small mt-3 mb-0',
        ],
    ],
];
