<?php

declare(strict_types=1);

return array(
    // 'name' => 'Growth Infrastructure',
    // 'slug' => 'growth-infrastructure',

    // 'seo' => [
    //     'title' => 'Growth Infrastructure Services | Skale',
    //     'description' => 'Connect your website, lead funnels, CRM, automation, integrations, and reporting into a growth system built around your business.',
    //     'canonical' => '/solutions/growth-infrastructure',
    //     'robots' => 'index,follow',
    //     'ogType' => 'website',
    //     'ogImage' => null,
    // ],

    'sections' => array(
        'hero' => array(
            'enabled' => true,
            'id' => 'growth-infrastructure-hero',
            'tag' => 'section',
            'class' => 'hero',
            'containerClass' => 'container',
            'rowClass' => 'row align-items-center g-5',
            'contentColumnClass' => 'col-lg-7',
            'formColumnClass' => 'col-lg-5',
            'contentClass' => 'hero-copy',
            'eyebrow' => 'Growth Infrastructure',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'Turn disconnected tools into a system that',
            'highlight' => 'drives growth.',
            'headingTag' => 'h1',
            'headingClass' => '',
            'highlightClass' => 'text-highlight',
            'description' => 'Skale connects your website, lead funnels, CRM, automation, and reporting so your business can attract better prospects, follow up faster, and convert more opportunities.',
            'descriptionClass' => 'hero-lead mt-4 mb-0',
            'benefits' => array(
                'class' => 'hero-checks',
                'ariaLabel' => 'Key benefits',
                'iconClass' => 'bi bi-check-circle-fill',
                'items' => array(
                    'Built around your business',
                    'Clear strategy before execution',
                    'One accountable growth partner',
                ),
            ),
            'buttons' => array(
                'wrapperClass' => 'd-flex flex-column flex-sm-row gap-3',
                'items' => array(
                    array(
                        'label' => 'Get Your Free Growth Review',
                        'url' => '#consultation',
                        'class' => 'btn btn-primary btn-lg',
                        'target' => null,
                        'rel' => null,
                    ),
                    array(
                        'label' => 'See How It Works',
                        'url' => '#how-it-works',
                        'class' => 'btn btn-outline-dark btn-lg',
                        'target' => null,
                        'rel' => null,
                    ),
                ),
            ),
            'note' => array(
                'text' => 'No pressure. No generic sales pitch. Just a practical conversation about what is holding your business back.',
                'class' => 'hero-note',
                'iconClass' => 'bi bi-shield-check',
            ),
            'form' => array(
                'enabled' => true,
                'anchorId' => 'consultation',
                'wrapperClass' => 'hero-form-wrap',
                'cardClass' => 'lead-form-card',
                'headerClass' => 'mb-4',
                'badge' => 'Free 30-minute consultation',
                'badgeClass' => 'badge text-bg-light border mb-3',
                'heading' => 'Find your biggest growth gap',
                'headingTag' => 'h2',
                'headingClass' => 'h3 mb-2',
                'description' => 'Tell us a little about your business. We will help you identify where leads, time, or revenue may be slipping through the cracks.',
                'descriptionClass' => 'mb-0',
                'action' => '/post-lead-form',
                'method' => 'POST',
                'id' => 'lead-form',
                'class' => 'ajaxForm',
                'attributes' => array(
                    'dataMetaFormName' => 'growth-infrastructure-form',
                    'dataMetaSuccessEvent' => 'Lead',
                ),
                'fields' => array(
                    array(
                        'type' => 'text',
                        'name' => 'name',
                        'id' => 'name',
                        'label' => 'Name',
                        'required' => true,
                        'autocomplete' => 'name',
                        'wrapperClass' => 'mb-3',
                        'labelClass' => 'form-label fw-semibold',
                        'inputClass' => 'form-control',
                    ),
                    array(
                        'type' => 'email',
                        'name' => 'email',
                        'id' => 'email',
                        'label' => 'Email',
                        'required' => true,
                        'autocomplete' => 'email',
                        'wrapperClass' => 'mb-3',
                        'labelClass' => 'form-label fw-semibold',
                        'inputClass' => 'form-control',
                    ),
                    array(
                        'type' => 'tel',
                        'name' => 'phone',
                        'id' => 'phone',
                        'label' => 'Phone',
                        'labelSuffix' => '(optional)',
                        'required' => false,
                        'autocomplete' => 'tel',
                        'wrapperClass' => 'col-sm-6',
                        'labelClass' => 'form-label fw-semibold',
                        'labelSuffixClass' => 'fw-normal text-secondary',
                        'inputClass' => 'form-control',
                        'group' => 'contact-details',
                    ),
                    array(
                        'type' => 'select',
                        'name' => 'team_size',
                        'id' => 'team',
                        'label' => 'Team size',
                        'required' => false,
                        'wrapperClass' => 'col-sm-6',
                        'labelClass' => 'form-label fw-semibold',
                        'inputClass' => 'form-select',
                        'group' => 'contact-details',
                        'options' => array(
                            array('label' => 'Select', 'value' => ''),
                            array('label' => 'Just me', 'value' => 'Just me'),
                            array('label' => '2-5 people', 'value' => '2-5 people'),
                            array('label' => '6-15 people', 'value' => '6-15 people'),
                            array('label' => '16-50 people', 'value' => '16-50 people'),
                            array('label' => '50+ people', 'value' => '50+ people'),
                        ),
                    ),
                    array(
                        'type' => 'textarea',
                        'name' => 'comment',
                        'id' => 'comment',
                        'label' => 'What is your biggest challenge?',
                        'placeholder' => 'Tell us what you want to improve...',
                        'required' => false,
                        'rows' => 4,
                        'wrapperClass' => 'mb-4',
                        'labelClass' => 'form-label fw-semibold',
                        'inputClass' => 'form-control',
                    ),
                    array(
                        'type' => 'hidden',
                        'name' => 'interests[]',
                        'value' => 'solutions',
                    ),
                ),
                'fieldGroups' => array(
                    'contact-details' => 'row g-3 mb-3',
                ),
                'submit' => array(
                    'label' => 'Request My Free Review',
                    'class' => 'btn btn-skale btn-lg w-100',
                ),
                'privacy' => array(
                    'text' => 'No sales pressure. Your information stays private.',
                    'class' => 'small text-secondary text-center mt-3 mb-0',
                    'iconClass' => 'fa-solid fa-lock me-1',
                ),
            ),
        ),

        'trustStrip' => array(
            'enabled' => true,
            'id' => 'trust-strip',
            'tag' => 'section',
            'class' => 'trust-strip',
            'containerClass' => 'container',
            'rowClass' => 'row row-cols-2 row-cols-lg-4 g-3',
            'columnClass' => 'col',
            'itemClass' => 'trust-item',
            'ariaLabel' => 'Why businesses trust Skale',
            'items' => array(
                array(
                    'iconClass' => 'bi bi-person-check',
                    'title' => 'Senior Expertise',
                    'description' => 'Direct access to an experienced partner',
                ),
                array(
                    'iconClass' => 'bi bi-diagram-3',
                    'title' => 'Systems Thinking',
                    'description' => 'Every tool supports a larger strategy',
                ),
                array(
                    'iconClass' => 'bi bi-graph-up-arrow',
                    'title' => 'Outcome Focused',
                    'description' => 'Decisions tied to measurable progress',
                ),
                array(
                    'iconClass' => 'bi bi-headset',
                    'title' => 'Ongoing Support',
                    'description' => 'A long-term partner after launch',
                ),
            ),
        ),

        'problems' => array(
            'enabled' => true,
            'id' => 'problems',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'introClass' => 'section-intro',
            'eyebrow' => 'The Real Problem',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'Your business may not need another tool. It may need its tools to work together.',
            'headingTag' => 'h2',
            'description' => 'Growth becomes harder when your website, marketing, sales process, customer data, and reporting operate separately. Small gaps create missed follow-ups, unclear performance, duplicated work, and lost opportunities.',
            'descriptionClass' => 'mt-3',
            'rowClass' => 'row g-4',
            'columnClass' => 'col-md-6 col-xl-3',
            'cardClass' => 'problem-card h-100',
            'iconWrapperClass' => 'icon-box',
            'titleClass' => 'h5',
            'bodyClass' => 'mb-0',
            'items' => array(
                array(
                    'iconClass' => 'bi bi-funnel',
                    'title' => 'Leads go nowhere',
                    'description' => 'Visitors arrive, but weak calls to action and disconnected follow-up leave good prospects behind.',
                ),
                array(
                    'iconClass' => 'bi bi-arrows-angle-contract',
                    'title' => 'Teams work manually',
                    'description' => 'Employees copy data, chase updates, and repeat tasks that should happen automatically.',
                ),
                array(
                    'iconClass' => 'bi bi-plug',
                    'title' => 'Systems are disconnected',
                    'description' => 'Customer information is spread across spreadsheets, inboxes, apps, and isolated platforms.',
                ),
                array(
                    'iconClass' => 'bi bi-bar-chart-line',
                    'title' => 'Results are unclear',
                    'description' => 'Reporting shows activity, but not which efforts are creating revenue or where improvement is needed.',
                ),
            ),
        ),

        'outcomes' => array(
            'enabled' => true,
            'id' => 'outcomes',
            'tag' => 'section',
            'class' => 'section-space pt-0',
            'containerClass' => 'container',
            'panelClass' => 'outcome-panel',
            'rowClass' => 'row align-items-center g-5',
            'contentColumnClass' => 'col-lg-5',
            'itemsColumnClass' => 'col-lg-7',
            'eyebrow' => 'The Outcome',
            'eyebrowClass' => 'eyebrow text-white',
            'heading' => 'A connected growth system built around how your business actually works.',
            'headingTag' => 'h2',
            'description' => 'Skale looks beyond isolated projects. We align strategy, technology, marketing, data, and operations so each part of your business supports the next.',
            'descriptionClass' => 'mt-3 mb-0',
            'listClass' => 'outcome-list',
            'iconClass' => 'bi bi-check-circle-fill',
            'items' => array(
                array(
                    'title' => 'Generate and capture better opportunities',
                    'description' => 'Clear messaging, stronger conversion paths, and lead-focused experiences.',
                ),
                array(
                    'title' => 'Respond faster and nurture consistently',
                    'description' => 'CRM workflows and automation keep prospects moving without constant manual effort.',
                ),
                array(
                    'title' => 'Make decisions with reliable data',
                    'description' => 'Reporting connects marketing activity and operational performance to business outcomes.',
                ),
                array(
                    'title' => 'Build a foundation that can scale',
                    'description' => 'Flexible systems support growth without creating unnecessary complexity or rework.',
                ),
            ),
        ),

        'serviceComponents' => array(
            'enabled' => true,
            'id' => 'service-components',
            'tag' => 'section',
            'class' => 'section-space bg-soft',
            'containerClass' => 'container',
            'headerRowClass' => 'row align-items-end mb-5 g-3',
            'headingColumnClass' => 'col-lg-8',
            'descriptionColumnClass' => 'col-lg-4',
            'eyebrow' => 'What We Connect',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'The essential parts of your growth engine.',
            'headingTag' => 'h2',
            'headingClass' => 'mb-0',
            'description' => 'Your engagement can include one area or a complete connected system, depending on your goals and current infrastructure.',
            'descriptionClass' => 'mb-0',
            'rowClass' => 'row g-4',
            'columnClass' => 'col-md-6 col-xl-4',
            'cardClass' => 'service-card h-100',
            'numberClass' => 'service-number',
            'iconWrapperClass' => 'icon-box',
            'titleClass' => 'h4',
            'listIconClass' => 'bi bi-check2',
            'items' => array(
                array(
                    'iconClass' => 'bi bi-window',
                    'title' => 'Website & Conversion',
                    'description' => 'Your website should clearly explain your value, establish credibility, and guide visitors toward action.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/website-design-and-development',
                    'bullets' => array(
                        'Website strategy and development',
                        'Landing pages and conversion paths',
                        'Messaging and calls to action',
                    ),
                ),
                array(
                    'iconClass' => 'bi bi-megaphone',
                    'title' => 'Marketing',
                    'description' => 'Reach the right audience with focused campaigns designed around qualified traffic and measurable action.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/marketing',
                    'bullets' => array(
                        'SEO and content strategy',
                        'PPC and paid social campaigns',
                        'Email marketing and nurturing',
                    ),
                ),
                array(
                    'iconClass' => 'bi bi-people',
                    'title' => 'CRM Solutions',
                    'description' => 'Create a dependable process for capturing, organizing, assigning, and following up with every opportunity.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/crm-solutions',
                    'bullets' => array(
                        'CRM setup and optimization',
                        'Lead routing and pipeline design',
                        'Sales and marketing alignment',
                    ),
                ),
                array(
                    'iconClass' => 'bi bi-lightning-charge',
                    'title' => 'Marketing Automation',
                    'description' => 'Remove repetitive work and make important actions happen reliably at the right time.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/marketing-automation',
                    'bullets' => array(
                        'Marketing and sales automation',
                        'Internal workflow automation',
                        'Notifications and follow-up sequences',
                    ),
                ),
                array(
                    'iconClass' => 'bi bi-link-45deg',
                    'title' => 'System Integrations',
                    'description' => 'Connect the platforms your business already depends on so information moves without unnecessary handoffs.',
                    'url' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/system-integrations',
                    'bullets' => array(
                        'API and platform integrations',
                        'Data synchronization',
                        'Custom integration workflows',
                    ),
                ),
                // [
                //     'iconClass' => 'bi bi-clipboard-data',
                //     'title' => 'Marketing Analytics',
                //     'description' => 'Understand what is working, what is not, and where your next best opportunity may be.',
                //     'url' => $_ENV['URL_SERVICES_SOLUTIONS'] . '/marketing-analytics',
                //     'bullets' => [
                //         'Analytics implementation',
                //         'Dashboards and reporting',
                //         'Continuous conversion optimization',
                //     ],
                // ],
            ),
            'cta' => array(
                'wrapperClass' => 'text-center mt-5',
                'label' => 'Talk Through Your Growth Gaps',
                'url' => '#consultation',
                'class' => 'btn btn-primary btn-lg',
            ),
        ),

        // Reserved for a separate related-services or individual-service listing component.
        // The source HTML does not contain an additional services section beyond serviceComponents.
        // 'services' => [
        //     'enabled' => false,
        //     'id' => 'services',
        //     'tag' => 'section',
        //     'class' => 'section-space',
        //     'containerClass' => 'container',
        //     'eyebrow' => '',
        //     'heading' => '',
        //     'description' => '',
        //     'rowClass' => 'row g-4',
        //     'columnClass' => 'col-md-6 col-xl-4',
        //     'cardClass' => 'service-card h-100',
        //     'items' => [],
        // ],

        'caseStudy' => array(
            'enabled' => true,
            'id' => 'case-study',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'panelClass' => 'case-study',
            'rowClass' => 'row align-items-center g-5',
            'contentColumnClass' => 'col-lg-6',
            'metricsColumnClass' => 'col-lg-6',
            'label' => 'Client Transformation',
            'labelClass' => 'case-label',
            'heading' => 'From fragmented processes to a scalable business platform.',
            'headingTag' => 'h2',
            'headingClass' => 'mt-2',
            'description' => 'A growing organization relied on disconnected tools, manual data handling, and a platform that could not support its expanding operation. Skale modernized the underlying systems, simplified workflows, and created a more dependable foundation for growth.',
            'descriptionClass' => 'mt-3',
            'lessonLabel' => 'The lesson:',
            'lesson' => 'Sustainable growth rarely comes from one isolated improvement. It comes from solving the system behind the problem.',
            'lessonClass' => 'mb-0',
            'lessonLabelClass' => 'text-dark',
            'metricsRowClass' => 'row g-3',
            'metricColumnClass' => 'col-6',
            'metricClass' => 'metric h-100',
            'metrics' => array(
                array('value' => '50%+', 'label' => 'Reduction in operating costs'),
                array('value' => '1M+', 'label' => 'Records supported at scale'),
                array('value' => 'Faster', 'label' => 'Publishing and delivery workflows'),
                array('value' => 'Unified', 'label' => 'Data, systems, and processes'),
            ),
            'disclaimer' => 'Use only metrics and claims you can verify. Add the client name, testimonial, or logo when permission is available.',
            'disclaimerClass' => 'small mt-3 mb-0',
        ),

        'process' => array(
            'enabled' => true,
            'id' => 'how-it-works',
            'tag' => 'section',
            'class' => 'section-space bg-soft',
            'containerClass' => 'container',
            'introClass' => 'section-intro',
            'eyebrow' => 'How It Works',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'A practical process with clarity at every step.',
            'headingTag' => 'h2',
            'description' => 'You will know what we are solving, why it matters, what happens next, and how success will be measured.',
            'descriptionClass' => 'mt-3',
            'rowClass' => 'row g-4',
            'columnClass' => 'col-md-6 col-xl-3',
            'cardClass' => 'process-card h-100',
            'stepClass' => 'process-step',
            'titleClass' => 'h5',
            'bodyClass' => 'mb-0',
            'items' => array(
                array(
                    'title' => 'Discover',
                    'description' => 'We learn how your business generates revenue, where work slows down, and what growth means to you.',
                ),
                array(
                    'title' => 'Prioritize',
                    'description' => 'We identify the highest-impact gaps and create a focused roadmap instead of trying to change everything at once.',
                ),
                array(
                    'title' => 'Build & Connect',
                    'description' => 'We improve the right experiences, workflows, integrations, campaigns, and reporting systems.',
                ),
                array(
                    'title' => 'Measure & Improve',
                    'description' => 'We monitor performance, learn from real behavior, and continuously improve what drives results.',
                ),
            ),
        ),

        'founder' => array(
            'enabled' => true,
            'id' => 'founder',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'panelClass' => 'founder-panel',
            'rowClass' => 'row align-items-center g-4',
            'avatarColumnClass' => 'col-lg-auto',
            'contentColumnClass' => 'col-lg',
            'buttonColumnClass' => 'col-lg-auto',
            'avatar' => array(
                'type' => 'initials',
                'value' => 'JB',
                'imageUrl' => null,
                'alt' => 'Joe Brown',
                'class' => 'founder-avatar',
            ),
            'quoteMark' => '“',
            'quoteMarkClass' => 'quote-mark',
            'heading' => 'You are not handed off to a junior team after the sale.',
            'headingTag' => 'h2',
            'headingClass' => 'h3',
            'description' => 'Skale is led by Joe Brown, a technology and growth partner with more than 20 years of experience helping businesses modernize systems, improve operations, and turn complex challenges into practical solutions.',
            'descriptionClass' => 'mb-2',
            'emphasis' => 'You receive senior-level thinking, direct communication, and recommendations based on what your business actually needs.',
            'emphasisClass' => 'mb-0',
            'emphasisTextClass' => 'text-dark',
            'cta' => array(
                'label' => 'Learn About Skale',
                'url' => '/about',
                'class' => 'btn btn-outline-dark',
            ),
        ),

        'qualification' => array(
            'enabled' => true,
            'id' => 'qualification',
            'tag' => 'section',
            'class' => 'section-space pt-0',
            'containerClass' => 'container',
            'rowClass' => 'row g-5 align-items-center',
            'contentColumnClass' => 'col-lg-6',
            'itemsColumnClass' => 'col-lg-6',
            'itemsRowClass' => 'row g-3',
            'itemColumnClass' => 'col-12',
            'itemClass' => 'd-flex gap-3 p-3 border rounded-4 h-100',
            'eyebrow' => 'Who This Is For',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'A strong fit for businesses ready to improve the system, not just patch the symptoms.',
            'headingTag' => 'h2',
            'iconClass' => 'bi bi-check-circle-fill text-success fs-5',
            'titleClass' => 'd-block',
            'descriptionClass' => 'text-secondary',
            'items' => array(
                array(
                    'title' => 'You are generating activity, but not enough qualified opportunities.',
                    'description' => 'Traffic, campaigns, and referrals are not consistently becoming customers.',
                ),
                array(
                    'title' => 'Your team relies on too many manual steps and disconnected tools.',
                    'description' => 'Growth is creating more work instead of greater efficiency.',
                ),
                array(
                    'title' => 'You want a long-term partner who can connect strategy and execution.',
                    'description' => 'You need more than a vendor completing isolated tasks.',
                ),
            ),
        ),

        'faq' => array(
            'enabled' => true,
            'id' => 'faq',
            'tag' => 'section',
            'class' => 'section-space bg-soft',
            'containerClass' => 'container',
            'rowClass' => 'row g-5',
            'introColumnClass' => 'col-lg-5',
            'accordionColumnClass' => 'col-lg-7',
            'eyebrow' => 'Common Questions',
            'eyebrowClass' => 'eyebrow',
            'heading' => 'What businesses usually want to know before getting started.',
            'headingTag' => 'h2',
            'description' => 'The first conversation is designed to determine fit and uncover opportunities. You do not need to have the solution figured out beforehand.',
            'descriptionClass' => 'mt-3',
            'accordionId' => 'growthFaq',
            'accordionClass' => 'accordion',
            'itemClass' => 'accordion-item',
            'headerClass' => 'accordion-header',
            'buttonClass' => 'accordion-button',
            'collapsedButtonClass' => 'accordion-button collapsed',
            'collapseClass' => 'accordion-collapse collapse',
            'openCollapseClass' => 'accordion-collapse collapse show',
            'bodyClass' => 'accordion-body',
            'allowMultipleOpen' => false,
            'items' => array(
                array(
                    'id' => 'faq-growth-infrastructure',
                    'question' => 'What exactly is growth infrastructure?',
                    'answer' => 'Growth infrastructure is the connected system behind how your business attracts prospects, captures leads, follows up, delivers information, measures results, and improves performance. It can include your website, CRM, automation, integrations, marketing, analytics, and operational workflows.',
                    'open' => true,
                ),
                array(
                    'id' => 'faq-current-tools',
                    'question' => 'Do we need to replace our current tools?',
                    'answer' => 'Not necessarily. Skale first evaluates what is already working. In many cases, the better answer is to improve, connect, or simplify the tools you already use rather than replace everything.',
                    'open' => false,
                ),
                array(
                    'id' => 'faq-one-priority',
                    'question' => 'Can we start with one priority?',
                    'answer' => 'Yes. Many engagements begin with the highest-impact issue, such as a website conversion problem, CRM setup, reporting gap, or manual workflow. The work can then expand based on results and business priorities.',
                    'open' => false,
                ),
                array(
                    'id' => 'faq-success',
                    'question' => 'How will we know the work is successful?',
                    'answer' => 'Success measures are defined before implementation. Depending on the engagement, they may include stronger conversion rates, faster response time, fewer manual steps, improved data accuracy, better lead quality, lower acquisition costs, or clearer reporting.',
                    'open' => false,
                ),
                array(
                    'id' => 'faq-consultation',
                    'question' => 'What happens during the free consultation?',
                    'answer' => 'We discuss your goals, current systems, biggest obstacles, and where you believe opportunities are being lost. You will leave with a clearer view of the problem and the most practical next step, whether or not we work together.',
                    'open' => false,
                ),
            ),
        ),

        'finalCta' => array(
            'enabled' => true,
            'id' => 'final-cta',
            'tag' => 'section',
            'class' => 'section-space',
            'containerClass' => 'container',
            'panelClass' => 'final-cta text-center',
            'rowClass' => 'row justify-content-center',
            'columnClass' => 'col-lg-9',
            'badge' => 'Start with clarity',
            'badgeClass' => 'badge rounded-pill text-bg-light mb-3',
            'heading' => 'Find out where your business is losing leads, time, or momentum.',
            'headingTag' => 'h2',
            'description' => 'Schedule a free consultation to talk through your current systems, your growth goals, and the most valuable place to begin.',
            'descriptionClass' => 'lead mt-3 mb-4',
            'buttons' => array(
                'wrapperClass' => 'd-flex flex-column flex-sm-row justify-content-center gap-3',
                'items' => array(
                    array(
                        'label' => 'Book My Free Consultation',
                        'url' => $_ENV['SITE_URL'] . $_ENV['URL_CONTACT'],
                        'class' => 'btn btn-primary btn-lg',
                        'iconClass' => null,
                    ),
                    array(
                        'label' => '732-925-4044',
                        'url' => 'tel:+17329254044',
                        'class' => 'btn btn-outline-light btn-lg',
                        'iconClass' => 'bi bi-telephone me-2',
                    ),
                ),
            ),
            'note' => 'No obligation. No generic package. A practical conversation focused on your business.',
            'noteClass' => 'small mt-3 mb-0',
        ),
    ),

    'form' => array(
        'heading' => '',
        'subheading' => '',
        'intro' => 'A few details are enough to get started.',
        'fields' => array(
            array(
                'divClass' => 'col-md-6',
                'fieldType' => 'input',
                'for' => 'name',
                'label' => 'Name',
                'type' => 'text',
                'id' => 'name',
                'name' => 'name',
                'class' => 'form-control',
                'autocomplete' => 'name',
                'required' => true,
            ),
            array(
                'divClass' => 'col-md-6',
                'fieldType' => 'input',
                'for' => 'email',
                'label' => 'Email',
                'type' => 'email',
                'id' => 'email',
                'name' => 'email',
                'class' => 'form-control',
                'autocomplete' => 'email',
                'required' => true,
            ),
            array(
                'divClass' => 'col-md-12',
                'fieldType' => 'input',
                'for' => 'website',
                'label' => 'Current Website <span class="fw-normal text-secondary">(optional)</span>',
                'type' => 'url',
                'id' => 'website',
                'name' => 'website',
                'class' => 'form-control',
                'placeholder' => 'https://',
                'required' => false,
            ),
            array(
                'divClass' => 'col-md-12',
                'fieldType' => 'select',
                'for' => 'challenge',
                'label' => 'What would you like to improve?',
                'id' => 'challenge',
                'name' => 'challenge',
                'class' => 'form-select',
                'options' => array(
                    array(
                        'value' => '',
                        'label' => 'Choose one',
                    ),
                    array(
                        'value' => 'new-website',
                        'label' => 'I need a new website',
                    ),
                    array(
                        'value' => 'redesign',
                        'label' => 'My current website needs a redesign',
                    ),
                    array(
                        'value' => 'conversion',
                        'label' => "We're getting traffic but not enough leads",
                    ),
                    array(
                        'value' => 'performance',
                        'label' => 'The site is slow or has technical problems',
                    ),
                    array(
                        'value' => 'wordpress',
                        'label' => 'I need WordPress help',
                    ),
                    array(
                        'value' => 'other',
                        'label' => 'Something else',
                    ),
                ),
            ),
            array(
                'divClass' => 'col-md-12',
                'fieldType' => 'textarea',
                'for' => 'comment',
                'label' => "Tell me what's happening",
                'id' => 'comment',
                'name' => 'comment',
                'class' => 'form-control',
                'placeholder' => '',
                'required' => true,
            ),
            array(
                'divClass' => 'col-md-12',
                'fieldType' => 'button',
                'for' => 'submit',
                'id' => 'submit',
                'name' => 'submit',
                'class' => 'btn-skale border-0 w-100',
                'value' => "Tell Me What's Not Working",
            ),
        ),
    )
);
